# -*- coding: utf-8 -*-
"""Command-line argument parser."""


import argparse

from MCP_Armor_Src.core.constants import (
    DEFAULT_NAMESPACE,
    DEFAULT_PACKAGE,
    DEFAULT_TAUNT_TEXT,
    PRESETS,
)


def build_arg_parser():
    parser = argparse.ArgumentParser(
        description='Python 3.13 MCPArmor host with a NetEase Python 2.7 target backend.')
    parser.add_argument('--debug', action='store_true', help='enable full staged [DEBUG] ... Loaded logs for source strings, payload, code tuple, opcode and execution')
    parser.add_argument('--header-mode', '--banner-mode', dest='header_mode', choices=['comment', 'docstring'], default='docstring', help='render the MCP Armor pixel header as comments or a lambda string literal')
    parser.add_argument('--output-date', dest='output_date', default='2012-03-15', help='watermark and emitted-pyc date (default: 2012-03-15)')
    parser.add_argument('input', nargs='?', help='input .py file or project folder')
    parser.add_argument('-o', '--output', default=None, help='output .py file or output folder')
    parser.add_argument('--config', default=None, help='read options from config.yml')
    parser.add_argument('--write-config', default=None, help='write example config.yml and exit')
    parser.add_argument('--python27', default=None, help='CPython 2.7 executable or installation directory used by the target backend')
    parser.add_argument('--static-check', dest='static_check', action='store_true', default=False, help='run source compliance checks before writing output')
    parser.add_argument('--no-static-check', dest='static_check', action='store_false', help='skip source compliance checks for this run')
    parser.add_argument('--show-hwid', action='store_true', help='print this machine encrypted HWID and exit without license validation')
    parser.add_argument('--folder', action='store_true', help='force folder mode')
    parser.add_argument('--obfuscate-init', action='store_true', help='obfuscate package __init__.py files instead of copying them')
    parser.add_argument('--emit-pyc', action='store_true', help='write the final Python 2.7 outer loader as a .pyc artifact')
    parser.add_argument('--preset', choices=sorted(PRESETS.keys()), default='safe', help='strength preset')
    parser.add_argument('--resource-profile', choices=['compact', 'balanced', 'strong', 'unlimited'], default='balanced', help='central size/performance governor for multiplicative transforms')
    parser.add_argument('--netease-profile', choices=['none', 'priority', 'safe', 'strong', 'strong-plus', 'diagnostic', 'netease-priority', 'priority-strong', 'netease-safe', 'netease-strong', 'netease-strong-plus', 'netease-diagnostic'], default='none', help='apply tested NetEase option bundle before per-option overrides')
    parser.add_argument('--key-len', type=int, default=16, help='payload key length')
    parser.add_argument('--payload-cipher', choices=['legacy', 'chacha'], default='legacy', help='outer payload cipher; chacha uses the NetEase _chacha module at runtime')
    parser.add_argument('--anti-debug', action='store_true', default=False, help='bind payload decryption to the behavior-pack UUID and NetEase native _chacha runtime')
    parser.add_argument('--experimental-anti-debug', action='store_true', default=False, help='enable experimental one-shot trace/profile/module/timing checks')
    parser.add_argument('--const-noise', type=int, default=None, help='override recursive co_consts noise density')
    parser.add_argument('--tail-noise', type=int, default=None, help='override unreachable safe bytecode trailer density')
    parser.add_argument('--loader-junk', type=int, default=None, help='override harmless fake loader function count')
    parser.add_argument('--trampoline-layers', type=int, default=None, help='override function-call trampoline layer count')
    parser.add_argument('--decoy-opcode-rows', type=int, default=None, help='override fake opcode decoy table row count')
    parser.add_argument('--fake-ref-layers', type=int, default=None, help='override fake function reference chain length')
    parser.add_argument('--dead-bad-bytecode', type=int, default=0, help='EXPERIMENTAL: append unreachable invalid bytecode islands per code object')
    parser.add_argument('--dead-bad-units', type=int, default=3, help='EXPERIMENTAL: invalid opcode units per dead island')
    parser.add_argument('--dead-nop-bloat', type=int, default=0, help='EXPERIMENTAL: NOP bytes inside each dead island')
    parser.add_argument('--dead-stop-bloat', type=int, default=0, help='EXPERIMENTAL: STOP_CODE bytes inside each dead island')
    parser.add_argument('--dead-arg-poison', type=int, default=0, help='EXPERIMENTAL: legal opcodes with out-of-range tuple args per dead island')
    parser.add_argument('--dead-exception-poison', type=int, default=0, help='EXPERIMENTAL: fake SETUP_FINALLY/SETUP_WITH/WITH_CLEANUP per dead island')
    parser.add_argument('--dead-call-poison', type=int, default=0, help='EXPERIMENTAL: fake MAKE_FUNCTION/CALL_FUNCTION with huge args per dead island')
    parser.add_argument('--metadata-poison', action='store_true', help='EXPERIMENTAL: poison co_name/co_filename/co_firstlineno inside payload')
    parser.add_argument('--metadata-binary', action='store_true', help='EXPERIMENTAL: use binary labels for poisoned metadata')
    parser.add_argument('--metadata-name-poison', action='store_true', help='EXPERIMENTAL: also poison safe non-lifecycle co_name values')
    parser.add_argument('--adaptive-strength', action='store_true', help='scale noise and dead islands by code object size/depth')
    parser.add_argument('--adaptive-max-scale', type=int, default=4, help='maximum adaptive strength multiplier')
    parser.add_argument('--fake-mcs-tables', type=int, default=3, help='fake MCS opcode map tables embedded in netease-func loader')
    parser.add_argument('--payload-splits', type=int, default=3, help='split encrypted payload base64 across multiple tags')
    parser.add_argument('--taunt-text', default=DEFAULT_TAUNT_TEXT, help='taunt text embedded as dead constants/fake references')
    parser.add_argument('--taunt-inner-consts', type=int, default=8, help='taunt constants per code object inside payload')
    parser.add_argument('--taunt-outer-refs', type=int, default=24, help='outer fake reference functions carrying taunt text')
    parser.add_argument('--bytecode-split-gates', action='store_true', help='insert safe bytecode split gates that jump over dead poison blocks')
    parser.add_argument('--bytecode-split-interval', type=int, default=18, help='instruction interval for bytecode split gates')
    parser.add_argument('--bytecode-split-bad-units', type=int, default=2, help='invalid opcode units inside each split gate dead block')
    parser.add_argument('--bytecode-split-nop-bloat', type=int, default=2, help='NOP bytes inside each split gate dead block')
    parser.add_argument('--fake-code-objects', type=int, default=0, help='fake nested code objects appended to co_consts')
    parser.add_argument('--fake-code-nop-bloat', type=int, default=0, help='extra NOP bytes inside each fake code object poison block')
    parser.add_argument('--fake-code-stop-bloat', type=int, default=0, help='extra STOP_CODE bytes inside each fake code object poison block')
    parser.add_argument('--ghost-names', type=int, default=24, help='ghost API/event names appended to co_names')
    parser.add_argument('--payload-graph-split', action='store_true', help='recover payload split tags through a fake dependency graph')
    parser.add_argument('--split-adaptive', action='store_true', help='adapt split gate density by code object size')
    parser.add_argument('--loop-shadow-gates', action='store_true', help='EXPERIMENTAL: add split gates near loop opcodes')
    parser.add_argument('--fake-payload-mirrors', type=int, default=2, help='fake encrypted payload mirror tables never used at runtime')
    parser.add_argument('--payload-graph-decoys', type=int, default=16, help='fake payload graph nodes ignored by graph resolver')
    parser.add_argument('--loader-decoy-tuples', type=int, default=0, help='dead loader branches carrying fake cPickle CodeType tuple payloads')
    parser.add_argument('--outer-decompiler-baits', type=int, default=0, help='cold recursive CodeType baits embedded in the outer loader for .pyc decompilers')
    parser.add_argument('--outer-decompiler-bait-budget', type=int, default=8192, help='hard source-byte budget for all outer decompiler baits in one module')
    parser.add_argument('--import-facade-layer', action='store_true', help='execute payload inside a dynamically materialized fake module and export its names')
    parser.add_argument('--reflection-metadata-decoy', action='store_true', help='apply harmless decoy __name__/__module__ metadata to the generated loader function')
    parser.add_argument('--module-registry-protection', action='store_true', help='use a loader-local module registry proxy; never replace NetEase global sys.modules')
    parser.add_argument('--outer-closure-vault', action='store_true', help='store outer runtime key and entry references in closure cells')
    parser.add_argument('--outer-tuple-gateway', action='store_true', help='route the real outer entry through Python 2 tuple arguments that emit genuine .0/.1 slots')
    parser.add_argument('--outer-closure-index-mirage', action='store_true', help='fragment outer key/entry state across indexed closure cells with plausible decoys')
    parser.add_argument('--outer-generator-frame-mirage', action='store_true', help='suspend one real and two decoy generator frames, then close all after outer execution')
    parser.add_argument('--outer-method-descriptor-mirage', action='store_true', help='materialize three bound method descriptors with one randomized real dispatch route')
    parser.add_argument('--outer-defaults-dict-doppelganger', action='store_true', help='split outer selection state across closure/defaults, restore decoy defaults and retain a false func_dict story')
    parser.add_argument('--outer-dynamic-method', action='store_true', help='bind the outer invocation method dynamically at runtime')
    parser.add_argument('--outer-dynamic-class', action='store_true', help='construct the outer runtime engine class through type()')
    parser.add_argument('--outer-callable-proxy', action='store_true', help='invoke the real loader through a dynamically built callable object')
    parser.add_argument('--outer-frame-namespace', action='store_true', help='obtain outer globals through generator.gi_frame without importing sys')
    parser.add_argument('--outer-generator-stages', action='store_true', help='run outer loader stages through a suspended generator')
    parser.add_argument('--outer-exception-state', action='store_true', help='drive outer loader stages through typed exceptions')
    parser.add_argument('--outer-no-sys-import', action='store_true', help='disable sys-dependent outer import facade and registry features')
    parser.add_argument('--opcode-restore-noise', type=int, default=12, help='dead arithmetic/try noise inside opcode restore function')
    parser.add_argument('--const-swamp', type=int, default=16, help='extra nested constant swamp per code object')
    parser.add_argument('--root-const-swamp', type=int, default=0, help='extra constant swamp only on root/module code object')
    parser.add_argument('--const-ref-chains', type=int, default=0, help='extra nested NetEase/API/opcode reference constants per code object')
    parser.add_argument('--api-decoy-refs', type=int, default=32, help='outer fake NetEase API reference functions')
    parser.add_argument('--real-block-reorder', action='store_true', help='EXPERIMENTAL: physically reorder simple straight-line bytecode blocks')
    parser.add_argument('--real-block-reorder-limit', type=int, default=2, help='maximum real block reorders per eligible code object')
    parser.add_argument('--safe-dead-blocks', action='store_true', help='EXPERIMENTAL: insert never-executed bytecode blocks')
    parser.add_argument('--bytecode-taken-jump-poison', action='store_true', help='insert LOAD_CONST True/POP_JUMP_IF_TRUE gates followed by unreachable invalid opcode poison')
    parser.add_argument('--safe-dead-interval', type=int, default=20, help='instruction interval for legal dead blocks')
    parser.add_argument('--safe-dead-width', type=int, default=4, help='legal junk operations per safe dead block')
    parser.add_argument('--safe-dead-limit', type=int, default=6, help='maximum safe dead blocks per code object')
    parser.add_argument('--bytecode-decoy-islands', action='store_true', help='insert verified legal opaque-entry decoy islands into cold functions')
    parser.add_argument('--bytecode-decoy-island-ratio', type=int, default=20, help='percentage of eligible functions selected for decoy islands')
    parser.add_argument('--bytecode-decoy-island-limit', type=int, default=2, help='maximum verified decoy islands per function')
    parser.add_argument('--bytecode-decoy-island-width', type=int, default=4, help='maximum legal junk operations per decoy island')
    parser.add_argument('--bytecode-decoy-island-growth', type=int, default=15, help='maximum bytecode growth percentage caused by decoy islands')
    parser.add_argument('--oparg-poison', action='store_true', help='DANGEROUS: use LOAD_CONST True/POP_JUMP_IF_TRUE gates followed by invalid opcode and out-of-range oparg poison')
    parser.add_argument('--bytecode-opaque-predicates', action='store_true', help='EXPERIMENTAL: insert never-taken legal opaque predicate bytecode blocks')
    parser.add_argument('--bytecode-opaque-interval', type=int, default=28, help='instruction interval for opaque predicate blocks')
    parser.add_argument('--bytecode-opaque-width', type=int, default=3, help='legal junk operations inside each opaque predicate branch')
    parser.add_argument('--bytecode-opaque-limit', type=int, default=4, help='maximum opaque predicate blocks per code object')
    parser.add_argument('--index-pool-shuffle', action='store_true', help='shuffle co_consts/co_names/safe co_varnames and remap bytecode indexes')
    parser.add_argument('--index-pool-mirrors', type=int, default=0, help='append unused duplicate const/name pool mirror entries before pool shuffle')
    parser.add_argument('--bytecode-stack-pad', type=int, default=0, help='inflate co_stacksize without changing runtime behavior')
    parser.add_argument('--bytecode-lnotab-noise', type=int, default=0, help='append noise pairs to co_lnotab for traceback/decompiler confusion')
    parser.add_argument('--bytecode-const-salts', type=int, default=0, help='append static salt constants to co_consts')
    parser.add_argument('--bytecode-name-chaff', type=int, default=0, help='append unused chaff entries to co_names')
    parser.add_argument('--bytecode-entry-noise', type=int, default=0, help='prepend legal stack-neutral bytecode noise to code objects')
    parser.add_argument('--bytecode-exception-decoys', type=int, default=0, help='prepend skipped SETUP_FINALLY/END_FINALLY decoy blocks to function code objects')
    parser.add_argument('--bytecode-stack-noise', action='store_true', help='insert internal LOAD_CONST/POP_TOP stack-equivalent noise blocks')
    parser.add_argument('--bytecode-stack-noise-interval', type=int, default=18, help='instruction interval between stack-equivalent noise blocks')
    parser.add_argument('--bytecode-stack-noise-limit', type=int, default=6, help='maximum stack-equivalent noise blocks per function code object')
    parser.add_argument('--bytecode-jump-inversion', '--bytecode-conditional-jump-inversion', dest='bytecode_jump_inversion', action='store_true', help='invert selected POP_JUMP_IF_FALSE/TRUE branches through an equivalent absolute jump')
    parser.add_argument('--bytecode-jump-inversion-limit', type=int, default=4, help='maximum conditional jump inversions per function code object')
    parser.add_argument('--bytecode-jump-trampolines', action='store_true', help='replace selected direct jumps with two-stage absolute jump chains')
    parser.add_argument('--bytecode-jump-trampoline-limit', type=int, default=4, help='maximum jump trampoline chains per function code object')
    parser.add_argument('--bytecode-flow', dest='bytecode_flow', action='store_true', help='ByteCode_Flow state dispatcher and verified conditional edge proxies')
    parser.add_argument('--bytecode-flow-ratio', dest='bytecode_flow_ratio', type=int, default=35, metavar='BYTECODE_FLOW_RATIO', help='ByteCode_Flow eligible-edge selection percentage')
    parser.add_argument('--bytecode-flow-max-edges', dest='bytecode_flow_max_edges', type=int, default=6, metavar='BYTECODE_FLOW_MAX_EDGES', help='ByteCode_Flow proxy edge limit per function')
    parser.add_argument('--bytecode-flow-loop-dispatch', dest='bytecode_flow_loop_dispatch', action='store_true', help='EXPERIMENTAL: route verified loop blocks through ByteCode_Flow dispatch')
    parser.add_argument('--bytecode-flow-block-seeds', dest='bytecode_flow_block_seeds', action='store_true', help='propagate verified seeds across ByteCode_Flow basic-block edges')
    parser.add_argument('--bytecode-flow-block-seed-ratio', dest='bytecode_flow_block_seed_ratio', type=int, default=35, metavar='BYTECODE_FLOW_BLOCK_SEED_RATIO', help='ByteCode_Flow block-seed selection percentage')
    parser.add_argument('--bytecode-flow-block-seed-max-blocks', dest='bytecode_flow_block_seed_max_blocks', type=int, default=64, metavar='BYTECODE_FLOW_BLOCK_SEED_MAX_BLOCKS', help='ByteCode_Flow block-seed limit')
    parser.add_argument('--bytecode-flow-block-shuffle', dest='bytecode_flow_block_shuffle', action='store_true', help='physically permute blocks for ByteCode_Flow')
    parser.add_argument('--bytecode-flow-block-shuffle-ratio', dest='bytecode_flow_block_shuffle_ratio', type=int, default=35, metavar='BYTECODE_FLOW_BLOCK_SHUFFLE_RATIO', help='ByteCode_Flow block-shuffle selection percentage')
    parser.add_argument('--bytecode-flow-block-shuffle-max-blocks', dest='bytecode_flow_block_shuffle_max_blocks', type=int, default=192, metavar='BYTECODE_FLOW_BLOCK_SHUFFLE_MAX_BLOCKS', help='ByteCode_Flow block-shuffle limit')
    parser.add_argument('--bytecode-cfg-flow', dest='bytecode_flow', action='store_true', default=argparse.SUPPRESS, help=argparse.SUPPRESS)
    parser.add_argument('--bytecode-cfg-flow-ratio', dest='bytecode_flow_ratio', type=int, default=argparse.SUPPRESS, help=argparse.SUPPRESS)
    parser.add_argument('--bytecode-cfg-flow-max-edges', dest='bytecode_flow_max_edges', type=int, default=argparse.SUPPRESS, help=argparse.SUPPRESS)
    parser.add_argument('--bytecode-cfg-loop-dispatch', dest='bytecode_flow_loop_dispatch', action='store_true', default=argparse.SUPPRESS, help=argparse.SUPPRESS)
    parser.add_argument('--bytecode-cfg-block-seeds', dest='bytecode_flow_block_seeds', action='store_true', default=argparse.SUPPRESS, help=argparse.SUPPRESS)
    parser.add_argument('--bytecode-cfg-block-seed-ratio', dest='bytecode_flow_block_seed_ratio', type=int, default=argparse.SUPPRESS, help=argparse.SUPPRESS)
    parser.add_argument('--bytecode-cfg-block-seed-max-blocks', dest='bytecode_flow_block_seed_max_blocks', type=int, default=argparse.SUPPRESS, help=argparse.SUPPRESS)
    parser.add_argument('--bytecode-cfg-block-shuffle', dest='bytecode_flow_block_shuffle', action='store_true', default=argparse.SUPPRESS, help=argparse.SUPPRESS)
    parser.add_argument('--bytecode-cfg-block-shuffle-ratio', dest='bytecode_flow_block_shuffle_ratio', type=int, default=argparse.SUPPRESS, help=argparse.SUPPRESS)
    parser.add_argument('--bytecode-cfg-block-shuffle-max-blocks', dest='bytecode_flow_block_shuffle_max_blocks', type=int, default=argparse.SUPPRESS, help=argparse.SUPPRESS)
    parser.add_argument('--bytecode-strategy-variation', action='store_true', help='deterministically vary active bytecode strategies and limits per code object')
    parser.add_argument('--bytecode-strategy-seed', type=int, default=0, help='reproducible seed for per-code bytecode strategy variation')
    parser.add_argument('--bytecode-delayed-const-access', '--bytecode-delayed-constants', dest='bytecode_delayed_const_access', action='store_true', help='replace selected LOAD_CONST operations with tuple/BINARY_SUBSCR indirection')
    parser.add_argument('--bytecode-delayed-const-limit', type=int, default=3, help='maximum delayed constant reads per function code object')
    parser.add_argument('--bytecode-extended-arg-prefix', action='store_true', help='prefix selected argument opcodes with a semantic no-op EXTENDED_ARG 0')
    parser.add_argument('--bytecode-extended-arg-interval', type=int, default=11, help='instruction interval used to select EXTENDED_ARG prefix sites')
    parser.add_argument('--bytecode-extended-arg-limit', type=int, default=6, help='maximum zero EXTENDED_ARG prefixes per function code object')
    parser.add_argument('--slot-mirage', action='store_true', help='code-object layer: rename cold non-argument fast-local slots to compiler-looking .N names without changing indexes')
    parser.add_argument('--slot-mirage-limit', type=int, default=8, help='maximum fast-local slots renamed by Slot Mirage per code object')
    parser.add_argument('--source-linearize-calls', action='store_true', help='source AST layer: split chained calls/attributes into ordered temporary variables')
    parser.add_argument('--source-schedule', action='store_true', help='source AST layer: extract pure expression atoms and reorder dependency-safe statements')
    parser.add_argument('--source-global-rename', dest='source_global_rename', action='store_true', default=True, help='project-wide scope-aware rename for definitions, imports, members, parameters and locals (enabled by default)')
    parser.add_argument('--no-source-global-rename', dest='source_global_rename', action='store_false', help='disable project-wide source rename')
    parser.add_argument('--source-module-rename', dest='source_module_rename', action='store_true', default=False, help='rename project Python filenames and relink imports plus NetEase registration paths')
    parser.add_argument('--no-source-module-rename', dest='source_module_rename', action='store_false', default=argparse.SUPPRESS, help='disable project Python filename rename')
    parser.add_argument('--source-module-rename-exclude', action='append', default=[], help='filename/path pattern excluded from module rename; repeatable')
    parser.add_argument('--write-rename-mapping', dest='write_rename_mapping', action='store_true', default=False, help='write ProGuard-style class/file rename mapping to the output folder')
    parser.add_argument('--no-write-rename-mapping', dest='write_rename_mapping', action='store_false', default=argparse.SUPPRESS, help='disable rename mapping report')
    parser.add_argument('--source-function-split', dest='source_function_split', action='store_true', default=False, help='folder AST layer: split eligible top-level functions into sibling modules before Rename')
    parser.add_argument('--no-source-function-split', dest='source_function_split', action='store_false', default=argparse.SUPPRESS, help='disable source function splitting')
    parser.add_argument('--source-string-split', action='store_true', help='source AST layer: split safe string literals into equivalent concatenations')
    parser.add_argument('--source-string-split-parts', type=int, default=3, help='maximum chunks used for source string splitting')
    parser.add_argument('--source-string-xor', action='store_true', help='source AST layer: XOR-encrypt ordinary str/unicode literals and decode them at runtime')
    parser.add_argument('--source-string-xor-mode', choices=['random', 'text', 'number', 'chacha'], default='random', help='string cipher mode: XOR variants or NetEase _chacha')
    parser.add_argument('--source-string-xor-text', default='MCP_Shiled', help='fixed text key used by --source-string-xor-mode text')
    parser.add_argument('--source-string-xor-number', type=int, default=173, help='fixed byte key (0-255) used by --source-string-xor-mode number')
    parser.add_argument('--source-string-xor-min-length', type=int, default=4, help='minimum string length eligible for source XOR encryption')
    parser.add_argument('--source-string-xor-limit', type=int, default=512, help='maximum XOR-encrypted string literals per file; 0 means no replacements')
    parser.add_argument('--source-string-xor-variants', type=int, default=4, help='maximum real decoder variants per file (2-8); small files adapt down automatically')
    parser.add_argument('--source-string-xor-decoys', type=int, default=2, help='maximum fake decoder variants per file (0-8); small files adapt down automatically')
    parser.add_argument('--source-string-xor-debug', action='store_true', help='emit [DEBUG] ... Loaded logs for decoder setup and every string decryption stage')
    parser.add_argument('--source-constant-pool', action='store_true', help='source AST layer: move safe repeated strings into a module-local constant pool')
    parser.add_argument('--source-constant-pool-min', type=int, default=4, help='minimum string length for source constant pool')
    parser.add_argument('--source-constant-pool-max', type=int, default=128, help='maximum source constant pool entries per file')
    parser.add_argument('--source-constant-rewrite', action='store_true', help='source AST layer: rewrite selected local integer constants as equivalent expressions')
    parser.add_argument('--source-constant-rewrite-limit', type=int, default=8, help='maximum local constants rewritten per function')
    parser.add_argument('--source-exception-shell', action='store_true', help='source AST layer: add safe exception shells around harmless local guards')
    parser.add_argument('--source-parenthesis-noise', action='store_true', help='source AST layer: add harmless redundant parentheses during source rendering')
    parser.add_argument('--source-comment-noise', action='store_true', help='source output layer: insert harmless randomized comments between top-level statements')
    parser.add_argument('--source-comment-noise-count', type=int, default=2, help='maximum randomized comment lines per source file')
    parser.add_argument('--source-dead-flow', action='store_true', help='source AST layer: inject unreachable fake branches/pseudo control flow')
    parser.add_argument('--source-dead-flow-blocks', type=int, default=1, help='maximum source dead-flow blocks per function/class/module')
    parser.add_argument('--source-vm', action='store_true', help='source AST layer: virtualize selected safe function bodies with a randomized register machine')
    parser.add_argument('--source-vm-ir', action='store_true', help='VM-IR class: enable full-coverage IR virtualization profile')
    parser.add_argument('--source-vm-extension', action='store_true', help='VM extension class: enable the legacy selective AST VM and its carrier extensions')
    parser.add_argument('--source-vm-full', action='store_true', help='virtualize every supported non-hot function with loops and expanded size limits')
    parser.add_argument('--source-vm-ratio', type=int, default=15, help='percentage of eligible functions selected for AST VM virtualization')
    parser.add_argument('--source-vm-min-ops', type=int, default=8, help='minimum AST node count for AST VM virtualization')
    parser.add_argument('--source-vm-max-ops', type=int, default=160, help='maximum AST node/instruction count for AST VM virtualization')
    parser.add_argument('--source-vm-max-functions', type=int, default=8, help='maximum virtualized functions per source file; 0 means unlimited')
    parser.add_argument('--source-vm-include', action='append', default=[], help='function-name glob eligible for AST VM; may be repeated')
    parser.add_argument('--source-vm-exclude', action='append', default=['On*', '*Tick*', '*Update*', '*Timer*', '*Frame*', '*Render*', 'Listen*', 'Notify*', 'NeteaseMod*', '__*__'], help='hot/compatibility function-name glob excluded from AST VM; may be repeated')
    parser.add_argument('--source-vm-allow-loops', action='store_true', help='allow AST VM virtualization of loops; disabled by default to protect hot-path performance')
    parser.add_argument('--source-vm-debug', action='store_true', help='emit a [DEBUG] log when the randomized AST VM runtime is installed')
    parser.add_argument('--source-flow-hardening', action='store_true', help='enable project call analysis, internal predicates, VM flow binding, dialects and cold exception traps')
    parser.add_argument('--source-project-analysis', action='store_true', help='scan the complete input folder before AST transformation and classify entry/hot/escaped functions')
    parser.add_argument('--source-internal-predicates', action='store_true', help='append synchronized hidden flow parameters only to closed same-module private functions')
    parser.add_argument('--source-internal-predicate-ratio', type=int, default=70, help='percentage of safely closed private functions selected for hidden flow parameters')
    parser.add_argument('--source-hot-pattern', action='append', default=[], help='function-name glob assigned a zero runtime-obfuscation budget; may be repeated')
    parser.add_argument('--source-vm-dialects', type=int, default=1, help='independent VM opcode/row dialect families per source module (1-8)')
    parser.add_argument('--source-vm-flow-constants', action='store_true', help='bind VM constants, names and block transitions to live flow predicates')
    parser.add_argument('--source-vm-exception-trap-ratio', type=int, default=0, help='percentage of cold VM block transitions guarded by a failure-only exception trap')
    parser.add_argument('--source-reference-obf', action='store_true', help='rewrite selected attribute/method reads through polymorphic encrypted getattr references')
    parser.add_argument('--source-reference-obf-ratio', type=int, default=35, help='percentage of eligible attribute/method references rewritten')
    parser.add_argument('--source-reference-obf-exclude', action='append', default=[], help='attribute-name glob excluded from reference obfuscation')
    parser.add_argument('--source-tuple-arg-decoys', type=int, default=0, help='AST layer: emit dead Python 2 tuple-argument decoys that naturally compile with .0 slots')
    parser.add_argument('--source-dotzero-relay', action='store_true', help='AST VM startup layer: carry the capability through a one-shot generator .0 relay')
    parser.add_argument('--source-default-capsule', action='store_true', help='AST/function-object layer: carry identity-weave fields in a one-shot function-default capsule')
    parser.add_argument('--source-identity-weave', action='store_true', help='AST/function-object layer: install real function code into a decoy public function at initialization')
    parser.add_argument('--source-identity-ratio', type=int, default=45, help='percentage of eligible functions selected for Identity Weave')
    parser.add_argument('--source-identity-max', type=int, default=12, help='maximum Identity Weave functions per source file')
    parser.add_argument('--source-identity-variation', action='store_true', help='randomize Identity Weave code/default/doc carrier roles and decoy body shapes')
    parser.add_argument('--source-decompiler-carriers', type=int, default=0, help='AST layer: add 1-4 cold recursive code-object carriers for decompiler stress')
    parser.add_argument('--source-decoy-docstrings', action='store_true', help='attach random binary docstrings to decompiler carrier functions')
    parser.add_argument('--source-decoy-docstring-min', type=int, default=1024, help='minimum random carrier docstring bytes')
    parser.add_argument('--source-decoy-docstring-max', type=int, default=4096, help='maximum random carrier docstring bytes')
    parser.add_argument('--source-exception-lattice', action='store_true', help='AST carrier layer: include nested try/except/else/finally control-flow traps')
    parser.add_argument('--source-class-body-trap', action='store_true', help='AST carrier layer: include nested class-body and method-role traps')
    parser.add_argument('--source-schedule-max-exprs', type=int, default=4, help='maximum pure expressions extracted per statement')
    parser.add_argument('--source-schedule-window', type=int, default=8, help='maximum adjacent simple statements considered for source scheduling')
    parser.add_argument('--control-flow-flatten', action='store_true', help='EXPERIMENTAL: source-level real while/state control-flow flattening')
    parser.add_argument('--control-flow-max-blocks', type=int, default=18, help='maximum top-level statements per function to flatten')
    parser.add_argument('--opcode-replacement', action='store_true', default=False, help='master switch for NetEase opcode replacement and opcode tunnels')
    parser.add_argument('--runtime-opcode-layer', action='store_true', help='EXPERIMENTAL: store payload under custom opcode map and restore to MCS opcodes at runtime')
    parser.add_argument('--per-code-runtime-opcode', action='store_true', help='EXPERIMENTAL: use independent runtime opcode map for each nested code object')
    parser.add_argument('--runtime-opcode-decoys', type=int, default=64, help='fake rows in encrypted runtime opcode table')
    parser.add_argument('--opcode-exclude', action='append', default=[], help='glob file to obfuscate without opcode remap/layer')
    parser.add_argument('--no-bytecode-obf', action='store_true', help='skip bytecode/code-object transforms for all files; keep source AST layers and loader wrapping')
    parser.add_argument('--source-only', action='append', default=[], help='glob file to skip bytecode transforms while keeping source AST layers')
    parser.add_argument('--ast-exclude', action='append', default=[], help='glob file to keep bytecode transforms but skip source AST layers')
    parser.add_argument('--loader-mode', choices=['source', 'marshal', 'function', 'cpickle', 'netease-func'], default='source', help='source is safest; cpickle is the compact recursive CodeTuple/lambda loader; function is the generic advanced loader; netease-func remaps payload to MCS opcode first')
    parser.add_argument('--loader-vm', dest='loader_vm', action='store_true', default=False, help='virtualize the loader crypto runtime')
    parser.add_argument('--no-loader-vm', dest='loader_vm', action='store_false', help='keep loader crypto runtime in direct form')
    parser.add_argument('--loader-dialect', choices=['auto', '0', '1', '2'], default='auto', help='CodeTuple loader source dialect')
    parser.add_argument('--code-tuple-payload', dest='code_tuple_payload', action='store_true', default=True, help='store bytecode payload as recursive cPickle CodeType tuple instead of marshal')
    parser.add_argument('--legacy-marshal-payload', '--no-code-tuple-payload', dest='code_tuple_payload', action='store_false', help='use legacy marshal payload format')
    parser.add_argument('--code-bytes-split', action='store_true', help='split co_code bytes inside recursive code-tuple payload and join them in loader')
    parser.add_argument('--code-bytes-split-min', type=int, default=48, help='minimum co_code byte length for code-byte split')
    parser.add_argument('--code-bytes-split-max-chunks', type=int, default=6, help='maximum co_code chunks per code object before depth decay')
    parser.add_argument('--code-bytes-fake-chunks', type=int, default=0, help='extra fake co_code chunks stored in split payload but never joined')
    parser.add_argument('--code-ref-table', action='store_true', help='store nested code objects in an external reference table and rebuild them dynamically')
    parser.add_argument('--code-ref-decoys', type=int, default=0, help='fake encrypted code tuple rows appended to the code ref table')
    parser.add_argument('--code-ref-wide-rows', action='store_true', help='append random junk fields to code ref rows while loader reads the real prefix')
    parser.add_argument('--code-ref-mask-markers', action='store_true', help='mask nested code reference marker ids inside co_consts')
    parser.add_argument('--code-tuple-field-shuffle', action='store_true', help='shuffle recursive CodeType tuple fields and restore them dynamically in loader')
    parser.add_argument('--code-tuple-fragments', action='store_true', help='split recursive CodeType tuple fields into shuffled fragment rows')
    parser.add_argument('--code-tuple-fragment-providers', action='store_true', help='wrap CodeType fragment rows as runtime provider records')
    parser.add_argument('--code-tuple-provider-graph', action='store_true', help='resolve CodeType fragment provider seeds through small dependency graph nodes')
    parser.add_argument('--code-tuple-provider-decoys', type=int, default=0, help='extra fake CodeType provider graph records per code tuple')
    parser.add_argument('--code-capsule-proxy', action='store_true', help='wrap final CodeType execution in a lazy callable capsule proxy')
    parser.add_argument('--code-capsule-protocol-guard', action='store_true', help='add capsule __getattribute__/pickle/copy/repr protocol guards')
    parser.add_argument('--lazy-function-capsules', action='store_true', help='store selected cold functions as independent encrypted payloads and materialize them on demand')
    parser.add_argument('--lazy-capsule-ratio', type=int, default=20, help='percentage of eligible functions moved into independent lazy payloads')
    parser.add_argument('--lazy-capsule-max-functions', type=int, default=8, help='maximum lazy function payloads per source file; 0 means unlimited')
    parser.add_argument('--lazy-capsule-mode', choices=['adaptive', 'once', 'call', 'count'], default='adaptive', help='lazy payload retention: once, every call, bounded call count, or adaptive')
    parser.add_argument('--lazy-capsule-retain-calls', type=int, default=4, help='number of calls retained before eviction in count/adaptive mode')
    parser.add_argument('--lazy-capsule-cross-key', action='store_true', help='bind lazy function payload keys to the outer module key during bootstrap')
    parser.add_argument('--lazy-capsule-rotate-payload', action='store_true', help='re-encrypt and re-key a lazy function payload after each hydration')
    parser.add_argument('--lazy-capsule-rotate-max-bytes', type=int, default=262144, help='maximum serialized lazy payload size eligible for runtime rotation; 0 disables size-qualified rotation')
    parser.add_argument('--lazy-capsule-carrier-swap', action='store_true', help='materialize lazy code by temporarily swapping it into an independent decoy function carrier')
    parser.add_argument('--lazy-capsule-manager-proxy', action='store_true', help='hide the lazy manager closure behind a dynamically built protocol-guarded callable object')
    parser.add_argument('--lazy-capsule-carrier-route-rotation', action='store_true', help='rotate carrier code writes across setattr, descriptor, and FunctionType channels')
    parser.add_argument('--lazy-capsule-include', action='append', default=[], help='function-name glob eligible for Lazy Capsule; may be repeated')
    parser.add_argument('--lazy-capsule-exclude', action='append', default=['On*', '*Tick*', '*Update*', '*Timer*', '*Frame*', '*Render*', 'Listen*', 'Notify*', 'NeteaseMod*', '__*__'], help='hot/compatibility function-name glob excluded from Lazy Capsule; may be repeated')
    parser.add_argument('--lazy-capsule-debug', action='store_true', help='print registry, hydration, and eviction diagnostics for Lazy Capsule')
    parser.add_argument('--code-field-descriptors', action='store_true', help='materialize the 14 CodeType fields through runtime descriptor/provider objects')
    parser.add_argument('--code-provider-context-bind', action='store_true', help='bind field providers to build/code/parent/field context')
    parser.add_argument('--code-fused-restore', action='store_true', help='fuse runtime opcode restoration into CodeType construction')
    parser.add_argument('--loader-reference-cleanup', action='store_true', help='clear payload/key/table/provider references before module execution')
    parser.add_argument('--code-global-arena', action='store_true', help='interleave every code object field in one module-wide reconstruction arena')
    parser.add_argument('--code-template-delta', action='store_true', help='rebuild arena code objects as field deltas over templates or earlier nodes')
    parser.add_argument('--code-global-arena-decoys', type=int, default=0, help='extra structurally valid decoy nodes/rows in the global code arena')
    parser.add_argument('--code-block-relocation', action='store_true', help='store shuffled basic blocks with symbolic jumps and relocate them in the loader')
    parser.add_argument('--code-block-reloc-decoys', type=int, default=0, help='extra fake basic-block records excluded from relocation order')
    parser.add_argument('--code-unit-arena', action='store_true', help='store co_code as shuffled instruction-unit records joined by the loader')
    parser.add_argument('--code-unit-arena-decoys', type=int, default=0, help='extra fake instruction-unit records excluded from the real order')
    parser.add_argument('--code-operand-graph', action='store_true', help='rebuild opcode and oparg bytes from masked symbolic fields at load time')
    parser.add_argument('--code-const-arena', action='store_true', help='move non-code co_consts entries into a shuffled module-wide arena')
    parser.add_argument('--code-const-arena-decoys', type=int, default=0, help='extra fake constant-arena rows excluded from real references')
    parser.add_argument('--code-const-provider-graph', action='store_true', help='resolve constant-arena values through masked dependency providers')
    parser.add_argument('--code-const-arena-limit', type=int, default=1024, help='maximum referenced constants moved per module; 0 means unlimited')
    parser.add_argument('--filename-mode', choices=['keep', 'mem', 'module'], default='mem', help='co_filename style')
    parser.add_argument('--include', action='append', default=None, help='include glob, default *.py')
    parser.add_argument('--exclude', action='append', default=[], help='exclude glob; modMain.py excluded by default')
    parser.add_argument('--obfuscate-modmain', action='store_true', help='also obfuscate modMain.py')
    parser.add_argument('--target-side', choices=['all', 'server', 'client'], default='all', help='folder mode side filter')
    parser.add_argument('--clean-output', action='store_true', help='delete output folder before writing')
    parser.add_argument('--copy-pyc', action='store_true', help='copy source .pyc/.pyo files; default skips them for NetEase')
    parser.add_argument('--deploy-target', default=None, help='after folder build, clear this folder and copy generated .py files into it')
    parser.add_argument('--fix-netease-register', action='store_true', help='fix RegisterSystem dotted class paths in copied modMain.py')
    parser.add_argument('--package-name', default=DEFAULT_PACKAGE, help='real output package/folder name')
    parser.add_argument('--namespace', default=DEFAULT_NAMESPACE, help='RegisterSystem namespace string')
    parser.add_argument('--inner-opcode-tunnel', action='store_true', help='EXPERIMENTAL: store payload under custom opcode map and restore before exec')
    parser.add_argument('--opcode-runtime', choices=['std', 'mcs'], default='std', help='opcode tunnel restore target')
    parser.add_argument('--mcs-opmap-version', type=int, default=1, help='NetEase opcode map version for --opcode-runtime mcs')
    return parser
