# -*- coding: utf-8 -*-
"""MCPArmor Easy 3.6 - compact ZKM-style front end.

The window deliberately keeps configuration out of the work area.  Six
commands (QLearn, Setting, input, Lang, Obf and Other) open focused dialogs;
the centre is a project browser/drop target and the lower-left is a status
line only.  Transformation is delegated to ``MCP_Armor_Src``.
"""
from __future__ import print_function

import json
import os
import queue
import ast
import ctypes
import re
import subprocess
import sys
import threading
import traceback
import datetime
import tkinter as tk
from tkinter import filedialog, messagebox, ttk
from ctypes import wintypes
from MCP_Armor_Src.utils.progress import parse_progress
from MCP_Armor_Src.cli.config import read_config_file
from .dialogs import ScrollDialog
from .settings_state import (AST_CHECKS, BYTE_CHECKS, ADVANCED_BYTE_CHECKS, VM_CHECKS,
                             AST_DEFAULTS, BYTE_DEFAULTS, default_settings, default_other, split_patterns)

from MCP_Armor_Src.hwid import encrypted_hwid, is_free_mode, validate_license


APP_VERSION = '3.6'
APP_TITLE = 'MCPArmor'
SITE = 'MCPArmor.opc2c.site'
COPYRIGHT = 'Copyright 2026-2026 MCP Teams All rights reserved'
BG, WHITE, PANEL, BORDER = '#eef1f5', '#ffffff', '#f7f9fb', '#bcc6d3'
TEXT, MUTED, BLUE, BLUE_DARK = '#1f2937', '#64748b', '#2f5d8a', '#24496f'
STATE_DIR = os.path.join(os.environ.get('LOCALAPPDATA', os.getcwd()), 'MCPArmor')
RUN_CONFIG = os.path.join(STATE_DIR, 'easy_run_config.yml')
RUN_LOG = os.path.join(STATE_DIR, 'easy_last_run.log')
CONFIG_SCHEMA = 'mcparmor-easyui'
CONFIG_VERSION = 1


def _app_dir():
    argv = os.path.abspath(sys.argv[0]) if sys.argv else ''
    if getattr(sys, 'frozen', False) or argv.lower().endswith('.exe'):
        return os.path.dirname(argv)
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


ROOT_DIR = _app_dir()
PY_EXTENSIONS = ('.py', '.pyc', '.pyo')
LOGO_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'assets', 'Logo.png')


def _logo_image(factor):
    """Load the supplied logo at a compact native Tk size."""
    try:
        return tk.PhotoImage(file=LOGO_PATH).subsample(factor, factor)
    except Exception:
        return None


def _find_cli():
    names = ('01_MCPArmor_CLI.exe', '01_MCPArmor_CLI_protected.exe', 'Py27ByteObf.exe')
    bases = (ROOT_DIR, os.path.dirname(ROOT_DIR), os.path.join(ROOT_DIR, '01_CLI'),
             os.path.join(ROOT_DIR, 'Pack_PyInstaller'))
    for base in bases:
        for name in names:
            path = os.path.join(base, name)
            if os.path.isfile(path):
                return path
    return None


def _safe_hwid():
    if is_free_mode():
        return 'free-mode'
    try:
        return encrypted_hwid()
    except Exception:
        return 'unavailable'


def _license_details():
    if is_free_mode():
        return 'free-mode', 'Free mode'
    code = _safe_hwid()
    try:
        status = validate_license(code=code)
        if status.reason == 'free_mode':
            return code, 'Free mode'
        return code, status.expires or ('not authorized' if not status.valid else 'unknown')
    except Exception:
        return code, 'unavailable'


def _scalar(value):
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, int):
        return str(value)
    text = '' if value is None else str(value)
    return '"' + text.replace('\\', '/').replace('"', '\\"') + '"'


def _yaml(sections):
    lines = ['# generated by MCPArmor Easy %s' % APP_VERSION]
    for section, values in sections:
        lines.append(section + ':')
        for key, value in values:
            if isinstance(value, list):
                lines.append('  %s:' % key)
                for item in value:
                    lines.append('    - %s' % _scalar(item))
            else:
                lines.append('  %s: %s' % (key, _scalar(value)))
    return '\n'.join(lines) + '\n'


def _config_bool(value, default=False):
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        low = value.strip().lower()
        if low in ('true', 'yes', 'on', '1'):
            return True
        if low in ('false', 'no', 'off', '0', ''):
            return False
    return bool(value) if value is not None else bool(default)


def _config_snapshot_payload(input_path, output_path, scope, language,
                             volume_level, target_mode, python27_path,
                             settings, other):
    """Return a JSON-safe, versioned EasyUI state snapshot."""
    return {
        'schema': CONFIG_SCHEMA,
        'version': CONFIG_VERSION,
        'input_path': str(input_path or ''),
        'output_path': str(output_path or ''),
        'scope': 'file' if scope == 'file' else 'folder',
        'language': language if language in ('中文', 'English') else '中文',
        'volume_level': volume_level if volume_level in (
            'compact', 'balanced', 'strong', 'unlimited', 'extended')
            else 'balanced',
        'target_mode': target_mode if target_mode in ('netease', 'native')
            else 'netease',
        'python27_path': str(python27_path or ''),
        'settings': dict(settings or {}),
        'other': dict(other or {}),
    }


def _config_yaml_state(payload):
    """Render a CLI-compatible YAML plus an exact EasyUI state section."""
    sections = [
        ('easyui_state', [
            ('schema', payload['schema']),
            ('version', payload['version']),
            ('input_path', payload['input_path']),
            ('output_path', payload['output_path']),
            ('scope', payload['scope']),
            ('language', payload['language']),
            ('volume_level', payload['volume_level']),
            ('target_mode', payload['target_mode']),
            ('python27_path', payload['python27_path']),
        ]),
        ('easyui_settings', list(payload['settings'].items())),
        ('easyui_other', list(payload['other'].items())),
    ]
    return _yaml(sections)


def validate_paths(src, dst, scope):
    if not src.strip() or not dst.strip(): raise ValueError('输入和输出均需填写 / Input and output required')
    a, b = (os.path.normcase(os.path.realpath(value.strip())) for value in (src, dst))
    if not os.path.exists(a): raise ValueError('输入不存在 / Input does not exist')
    if a == b: raise ValueError('输出与输入相同 / Output equals input')
    try: common = os.path.commonpath([a, b])
    except ValueError: common = None
    if scope == 'folder' and common in (a, b):
        raise ValueError('输入输出目录应相互独立 / Input and output directories must not overlap')
    if scope == 'file' and os.path.isdir(b): raise ValueError('单文件模式需要输出文件名 / Output filename required')
    return True


class LicenseSplash(tk.Toplevel):
    def __init__(self, master, hwid, expires, on_accept):
        tk.Toplevel.__init__(self, master)
        self.title(APP_TITLE)
        self.resizable(False, False)
        self.configure(bg=WHITE)
        self.protocol('WM_DELETE_WINDOW', master.destroy)
        self.grab_set()
        outer = tk.Frame(self, bg=WHITE, bd=1, relief='solid')
        outer.pack(fill='both', expand=True, padx=4, pady=4)
        self.logo = _logo_image(5)
        tk.Label(outer, image=self.logo, text='' if self.logo else APP_TITLE, bg=WHITE, fg='#111827',
                 font=('Segoe UI', 25, 'bold')).pack(pady=(12, 2))
        tk.Label(outer, text='version %s' % APP_VERSION, bg=WHITE, fg=TEXT,
                 font=('Segoe UI', 10, 'bold')).pack(pady=2)
        tk.Label(outer, text=COPYRIGHT, bg=WHITE, fg=TEXT,
                 font=('Segoe UI', 10, 'bold')).pack(pady=(11, 2))
        tk.Label(outer, text=SITE, bg=WHITE, fg=TEXT,
                 font=('Segoe UI', 10, 'bold')).pack(pady=(2, 18))
        info = tk.Frame(outer, bg=PANEL, bd=1, relief='sunken')
        info.pack(fill='x', padx=10, pady=(0, 18))
        self.detail_vars = {}
        for label, value in (('HWID:', hwid), ('Time:', expires)):
            row = tk.Frame(info, bg=PANEL)
            row.pack(fill='x', padx=18, pady=4)
            tk.Label(row, text=label, width=9, anchor='e', bg=PANEL, fg=TEXT,
                     font=('Segoe UI', 10, 'bold')).pack(side='left')
            var = tk.StringVar(value=value)
            self.detail_vars[label] = var
            tk.Label(row, textvariable=var, anchor='w', bg=PANEL, fg=TEXT,
                     font=('Segoe UI', 10)).pack(side='left', padx=8)
        buttons = tk.Frame(outer, bg=WHITE)
        buttons.pack(fill='x', padx=10, pady=(0, 14))
        ttk.Button(buttons, text='I agree', command=on_accept).pack(side='left', expand=True, padx=(7, 4), ipadx=12)
        ttk.Button(buttons, text="I don't agree", command=master.destroy).pack(side='right', expand=True, padx=(4, 7), ipadx=12)

    def set_expiry(self, value):
        if 'Time:' in self.detail_vars:
            self.detail_vars['Time:'].set(value)


class EasyApp(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)
        self.withdraw()
        self.title('%s %s Free' % (APP_TITLE, APP_VERSION))
        self.geometry('1120x720')
        self.minsize(900, 560)
        self.configure(bg=BG)
        self.input_path = tk.StringVar()
        self.output_path = tk.StringVar()
        self.scope = 'folder'
        self.language = '中文'
        self.volume_level = 'balanced'
        self.target_mode = 'netease'
        self.python27_path = tk.StringVar(value=self._find_python27())
        self.status = tk.StringVar(value='Status: Ready')
        self.hwid, self.expiry = _safe_hwid(), 'Checking...'
        self.running = False
        self.events = queue.Queue()
        self._drop_queue = queue.Queue()
        self.settings = self._default_settings()
        self.other = default_other()
        self._qlearn_active = False
        self._qlearn_step = None
        self._qlearn_prompted = False
        self._obf_done_callback = None
        self.last_run_output = ''
        self._file_progress = None
        self._log_views = []
        self._style()
        self.after(100, self._poll_events)
        self._show_splash()

    def _default_settings(self):
        return default_settings()

    @staticmethod

    def _find_python27():
        candidates = (os.environ.get('MCPARMOR_PY27', ''), r'C:\Python27\python.exe',
                      r'C:\Python27\pythonw.exe')
        for path in candidates:
            if path and os.path.isfile(path):
                return path
        return ''

    def _style(self):
        style = ttk.Style(self)
        try:
            style.theme_use('clam')
        except tk.TclError:
            pass
        style.configure('TFrame', background=BG)
        style.configure('TLabel', background=BG, foreground=TEXT, font=('Segoe UI', 10))
        style.configure('Title.TLabel', background=BG, foreground=TEXT, font=('Segoe UI', 22, 'bold'))
        style.configure('Muted.TLabel', background=BG, foreground=MUTED)
        style.configure('TButton', padding=(12, 7), font=('Segoe UI', 10))
        style.configure('Tool.TButton', padding=(16, 10), font=('Segoe UI', 10, 'bold'), borderwidth=1)
        style.configure('Accent.TButton', background=BLUE, foreground=WHITE, padding=(16, 10), font=('Segoe UI', 10, 'bold'), borderwidth=1)
        style.map('Accent.TButton', background=[('active', BLUE_DARK)])
        style.configure('TLabelframe', background=WHITE, bordercolor=BORDER)
        style.configure('TLabelframe.Label', background=WHITE, foreground=TEXT, font=('Segoe UI', 10, 'bold'))

    def _show_splash(self):
        try:
            splash = LicenseSplash(self, self.hwid, self.expiry, self._accept_splash)
            self._license_splash = splash
            splash.update_idletasks()
            x = (self.winfo_screenwidth() - splash.winfo_width()) // 2
            y = (self.winfo_screenheight() - splash.winfo_height()) // 2
            splash.geometry('+%d+%d' % (max(0, x), max(0, y)))
            splash.lift(); splash.focus_force()
            threading.Thread(target=self._license_worker, daemon=True).start()
        except Exception:
            self._accept_splash()

    def _license_worker(self):
        code, expiry = _license_details()
        self.events.put(('license', code, expiry))

    def _accept_splash(self):
        for child in list(self.winfo_children()):
            if isinstance(child, tk.Toplevel):
                try: child.grab_release()
                except Exception: pass
                child.destroy()
        if not getattr(self, '_main_built', False):
            self._build_main()
            self._main_built = True
        self.deiconify()
        self._set_status('状态：就绪' if self.language == '中文' else 'Status: Ready')
        if not self._qlearn_prompted:
            self._qlearn_prompted = True
            self.after(250, self._prompt_qlearn)

    def _build_main(self):
        self._build_menu()
        root = tk.Frame(self, bg=BG)
        # Keep the work area flush beneath the native menu, like ZKM.  The
        # former six-button strip and large HWID/title banner were removed;
        # actions now live in the menus and License is available in Setting.
        root.pack(fill='both', expand=True, padx=8, pady=6)
        body = tk.PanedWindow(root, orient='horizontal', sashwidth=5, bg=BORDER, bd=0)
        body.pack(fill='both', expand=True, pady=(0, 8))
        self._build_tree(body)
        self._build_workspace(body)
        self._enable_native_drop()
        strip = tk.Frame(root, bg=WHITE, bd=1, relief='solid', height=30)
        strip.pack(fill='x')
        strip.pack_propagate(False)
        tk.Label(strip, textvariable=self.status, bg=WHITE, fg=TEXT, anchor='w').pack(fill='both', padx=8)

    def _build_menu(self):
        label = lambda en, cn: cn if self.language == '中文' else en
        menu = tk.Menu(self)
        for en, cn, actions in (
            ('File', '文件', [('Input', '输入', self.open_input), ('Obf', '混淆', self.open_obf), ('Log', '日志', self.open_log), ('Exit', '退出', self.destroy)]),
            ('Configuration', '配置', [('Save config', '保存配置', self.save_config), ('Load config', '加载配置', self.load_config)]),
            ('Tools', '工具', [('QLearn', '快速引导', self.open_qlearn), ('Setting', '混淆设置', self.open_setting), ('Loader', '加载器设置', self.open_loader), ('Other', '其他设置', self.open_other)]),
            ('Options', '选项', [('Lang', '语言', self.open_lang)]),
            ('Help', '帮助', [('License', '许可证', self.open_license), ('About', '关于', self.open_about)])):
            child = tk.Menu(menu, tearoff=False)
            for a, b, command in actions: child.add_command(label=label(a, b), command=command)
            menu.add_cascade(label=label(en, cn), menu=child)
        # Keep Update log as a top-level command beside Help, matching the
        # compact ZKM-style menu bar rather than nesting it under Help.
        menu.add_command(label=label('Update log', '更新日志'), command=self.open_update_log)
        self.config(menu=menu)

    def _t(self, key):
        chinese = {
            'tree': '类 / 函数',
            'drop_title': '将 .py 文件或文件夹拖入此处',
            'drop_hint': '也可点击此区域，或通过 File → Input 选择目标',
            'drop_bad': '状态：请拖入 .py、.pyc、.pyo 文件或文件夹',
            'dropped': '状态：已设置拖入的输入目标',
        }
        english = {
            'tree': 'Classes / functions',
            'drop_title': 'Drop a .py file or folder here',
            'drop_hint': 'Use File → Input to browse and select a target',
            'drop_bad': 'Status: Drop a .py, .pyc, .pyo file or folder',
            'dropped': 'Status: Input dropped',
        }
        return (chinese if self.language == '中文' else english)[key]

    def _apply_language(self):
        if hasattr(self, 'tree_title_var'):
            self.tree_title_var.set(self._t('tree'))
            self.drop_title_var.set(self._t('drop_title'))
            self.drop_hint_var.set(self._t('drop_hint'))
        self._build_menu()

    def _build_tree(self, parent):
        pane = tk.Frame(parent, bg=WHITE, bd=1, relief='solid', width=250)
        pane.pack_propagate(False); parent.add(pane, minsize=190)
        self.tree_title_var = tk.StringVar(value=self._t('tree'))
        tk.Label(pane, textvariable=self.tree_title_var, bg=WHITE, fg=TEXT, anchor='w', font=('Segoe UI', 12, 'bold')).pack(fill='x', padx=12, pady=(12, 6))
        self.tree = ttk.Treeview(pane, show='tree', selectmode='browse')
        scroll = ttk.Scrollbar(pane, orient='vertical', command=self.tree.yview)
        self.tree.configure(yscrollcommand=scroll.set); scroll.pack(side='right', fill='y')
        self.tree.pack(side='left', fill='both', expand=True, padx=(8, 0), pady=6)
        self.tree.bind('<<TreeviewSelect>>', self._tree_select)

    def _build_workspace(self, parent):
        pane = tk.Frame(parent, bg=BG); parent.add(pane, minsize=560)
        self.drop = tk.Frame(pane, bg=WHITE, bd=1, relief='solid')
        self.drop.pack(fill='both', expand=True, padx=8, pady=8)
        self.drop_title_var = tk.StringVar(value=self._t('drop_title'))
        self.drop_hint_var = tk.StringVar(value=self._t('drop_hint'))
        tk.Label(self.drop, textvariable=self.drop_title_var, bg=WHITE, fg=BLUE,
                 font=('Microsoft YaHei UI', 22, 'bold')).pack(expand=True, pady=(65, 4))
        tk.Label(self.drop, textvariable=self.drop_hint_var, bg=WHITE, fg=MUTED,
                 font=('Microsoft YaHei UI', 10)).pack(pady=(0, 65))
        self.drop.bind('<Button-1>', lambda _e: self.open_input())

    def _enable_native_drop(self):
        """Enable Explorer file/folder drops without a third-party Tk DLL."""
        if os.name != 'nt':
            return
        try:
            self._drop_procs = []
            shell32 = ctypes.windll.shell32
            user32 = ctypes.windll.user32
            ptr = ctypes.c_void_p
            shell32.DragAcceptFiles.argtypes = [wintypes.HWND, wintypes.BOOL]
            shell32.DragAcceptFiles.restype = None
            shell32.DragQueryFileW.argtypes = [wintypes.HANDLE, wintypes.UINT, wintypes.LPWSTR, wintypes.UINT]
            shell32.DragQueryFileW.restype = ctypes.c_uint
            shell32.DragFinish.argtypes = [wintypes.HANDLE]
            shell32.DragFinish.restype = None
            user32.GetWindowLongPtrW.argtypes = [wintypes.HWND, ctypes.c_int]
            user32.GetWindowLongPtrW.restype = ctypes.c_void_p
            user32.SetWindowLongPtrW.argtypes = [wintypes.HWND, ctypes.c_int, ctypes.c_void_p]
            user32.SetWindowLongPtrW.restype = ctypes.c_void_p
            user32.CallWindowProcW.argtypes = [ctypes.c_void_p, wintypes.HWND,
                                                wintypes.UINT, wintypes.WPARAM, wintypes.LPARAM]
            user32.CallWindowProcW.restype = ctypes.c_ssize_t
            wndproc_type = ctypes.WINFUNCTYPE(ctypes.c_ssize_t, wintypes.HWND,
                                               wintypes.UINT, wintypes.WPARAM, wintypes.LPARAM)
            def install(widget):
                hwnd = widget.winfo_id()
                shell32.DragAcceptFiles(hwnd, True)
                old_proc = user32.GetWindowLongPtrW(hwnd, -4)

                def wndproc(window, message, wparam, lparam):
                    if message == 0x0233:
                        try:
                            count = shell32.DragQueryFileW(wparam, 0xFFFFFFFF, None, 0)
                            for index in range(count):
                                buf = ctypes.create_unicode_buffer(32768)
                                shell32.DragQueryFileW(wparam, index, buf, len(buf))
                                if buf.value: self._drop_queue.put(buf.value)
                        except Exception:
                            self.events.put(('log', traceback.format_exc()))
                        finally: shell32.DragFinish(wparam)
                        return 0
                    return user32.CallWindowProcW(old_proc, window, message, wparam, lparam)

                callback = wndproc_type(wndproc)
                user32.SetWindowLongPtrW(hwnd, -4, ctypes.cast(callback, ctypes.c_void_p))
                self._drop_procs.append((hwnd, old_proc, callback))

            # Explorer sends WM_DROPFILES to the child window under the
            # pointer, so register both the top-level and the centre target.
            install(self)
            if hasattr(self, 'drop'):
                install(self.drop)
                for child in self.drop.winfo_children(): install(child)
        except Exception:
            self.events.put(('log', traceback.format_exc()))

    def _accept_drop(self, path):
        path = os.path.abspath(path)
        if not (os.path.isfile(path) or os.path.isdir(path)):
            return
        if os.path.isfile(path) and not path.lower().endswith(PY_EXTENSIONS):
            self._set_status(self._t('drop_bad'))
            return
        self.input_path.set(path)
        self.scope = 'file' if os.path.isfile(path) else 'folder'
        self._refresh_tree(path)
        self._set_status(self._t('dropped'))

    def _set_status(self, value):
        self.status.set(value)

    def _update_file_progress(self, event):
        """Render the worker's current file as ``13/81 py:name.py``."""
        self._file_progress = event
        zh = self.language == '中文'
        prefix = '状态' if zh else 'Status'
        state = event.get('state')
        verb = {'start': '混淆中' if zh else 'Obfuscating',
                'done': '已完成' if zh else 'Processed',
                'error': '混淆失败' if zh else 'Failed'}.get(state, state)
        self._set_status('%s: %s %d/%d  py:%s' % (
            prefix, verb, event['index'], event['total'], event['path']))

    def _progress_failure_status(self, code):
        event = getattr(self, '_file_progress', None)
        prefix = '状态' if self.language == '中文' else 'Status'
        if event is not None and event.get('state') in ('start', 'error'):
            return '%s: %s (%s) %d/%d  py:%s - Log' % (
                prefix, '混淆失败' if self.language == '中文' else 'Failed',
                code, event['index'], event['total'], event['path'])
        return '%s: %s (%s) - Log' % (
            prefix, '失败' if self.language == '中文' else 'Failed', code)

    def _tree_select(self, _event=None):
        sel = self.tree.selection()
        if sel:
            values = self.tree.item(sel[0], 'values')
            if values: self._set_status('Status: ' + values[0])

    def _python_symbols(self, path):
        """Read top-level classes/functions for the ZKM-like file tree."""
        text = ''
        try:
            with open(path, 'rb') as handle:
                text = handle.read().decode('utf-8-sig', 'replace')
            module = ast.parse(text, path)
            result = []
            for node in module.body:
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                    kind = 'class' if isinstance(node, ast.ClassDef) else 'function'
                    result.append((kind, node.name))
            return result
        except Exception:
            return [('function' if match.group(1) == 'def' else 'class', match.group(2))
                    for match in re.finditer(r'^\s*(def|class)\s+([A-Za-z_][A-Za-z0-9_]*)', text, re.M)]

    def _add_python_node(self, parent, path):
        node = self.tree.insert(parent, 'end', text=os.path.basename(path), values=(path,))
        if path.lower().endswith('.py'):
            for kind, name in self._python_symbols(path):
                self.tree.insert(node, 'end', text='%s: %s' % (kind, name), values=(path,))

    def _folder_has_python(self, path):
        try:
            return any(name.lower().endswith(PY_EXTENSIONS)
                       for _base, _dirs, files in os.walk(path)
                       for name in files)
        except OSError:
            return False

    def _insert_folder(self, parent, path):
        try:
            entries = sorted(os.listdir(path), key=lambda x: (not os.path.isdir(os.path.join(path, x)), x.lower()))
        except OSError:
            return
        for name in entries:
            child = os.path.join(path, name)
            if os.path.isdir(child):
                if self._folder_has_python(child):
                    branch = self.tree.insert(parent, 'end', text=name, values=(child,), open=True)
                    self._insert_folder(branch, child)
            elif name.lower().endswith(PY_EXTENSIONS):
                self._add_python_node(parent, child)

    def _refresh_tree(self, path):
        if not hasattr(self, 'tree'): return
        self.tree.delete(*self.tree.get_children())
        if os.path.isfile(path):
            self._add_python_node('', path); return
        root = self.tree.insert('', 'end', text=os.path.basename(path) or path, values=(path,), open=True)
        self._insert_folder(root, path)

    def _entry(self, parent, row, label, var, browse):
        ttk.Label(parent, text=label, width=12).grid(row=row, column=0, sticky='w', padx=8, pady=8)
        ttk.Entry(parent, textvariable=var).grid(row=row, column=1, sticky='ew', padx=5, pady=8)
        ttk.Button(parent, text='Browse', command=browse).grid(row=row, column=2, padx=8, pady=8)
        parent.columnconfigure(1, weight=1)

    def _choose_input(self, var=None):
        path = filedialog.askopenfilename(filetypes=[('Python', '*.py'), ('All files', '*.*')])
        if path:
            self.input_path.set(path); self.scope = 'file'; self._refresh_tree(path)
            if var is not None: var.set(path)

    def _choose_folder(self, var=None):
        path = filedialog.askdirectory()
        if path:
            self.input_path.set(path); self.scope = 'folder'; self._refresh_tree(path)
            if var is not None: var.set(path)

    def open_input(self, on_done=None, on_cancel=None):
        label = lambda en, cn: cn if self.language == '中文' else en
        win = ScrollDialog(self, label('Input', '输入'), 690, 270, on_cancel)
        win.field(win.body, 'input', label('Input file / folder', '输入文件 / 文件夹'), self.input_path.get())
        def browse(folder=False):
            path = filedialog.askdirectory(parent=win) if folder else filedialog.askopenfilename(parent=win, filetypes=[('Python', '*.py *.pyc *.pyo')])
            if path: win.vars['input'].set(path)
        row = ttk.Frame(win.body); row.pack(fill='x')
        ttk.Button(row, text=label('File', '文件'), command=browse).pack(side='left')
        ttk.Button(row, text=label('Folder', '文件夹'), command=lambda: browse(True)).pack(side='left', padx=6)
        def accept():
            path = os.path.abspath(win.vars['input'].get().strip())
            if not os.path.exists(path) or (os.path.isfile(path) and not path.lower().endswith(PY_EXTENSIONS)):
                messagebox.showerror(APP_TITLE, label('Select a Python file or folder.', '请选择 Python 文件或文件夹。'), parent=win); return
            self._accept_drop(path)
            win.close()
            if on_done: self.after(10, on_done)
        win.button(label('Cancel', '取消'), win.cancel)
        win.button('OK', accept)
        return win

    def _choose_output(self, var=None):
        path = filedialog.askdirectory()
        if path:
            self.output_path.set(path)
            if var is not None: var.set(path)

    def open_output(self, on_done=None, on_cancel=None):
        label = lambda en, cn: cn if self.language == '中文' else en
        if not os.path.exists(self.input_path.get().strip()):
            messagebox.showerror(APP_TITLE, label('Select input first.', '请先选择输入。'), parent=self)
            if on_cancel: on_cancel()
            return
        win = ScrollDialog(self, label('Obf output', '混淆输出'), 690, 300, on_cancel)
        win.field(win.body, 'output', label('Output path', '输出路径'), self.output_path.get())
        def browse():
            path = filedialog.askdirectory(parent=win) if self.scope == 'folder' else filedialog.asksaveasfilename(parent=win, defaultextension='.py', filetypes=[('Python', '*.py')])
            if path: win.vars['output'].set(path)
        ttk.Button(win.body, text=label('Browse', '浏览'), command=browse).pack(anchor='e')
        ttk.Label(win.body, text=label('Please enter your artifact output path. Do not overwrite the original path. Confirm your backup and configuration.', '请输入产物位置。不要覆盖原路径；请确认已有备份并检查配置。'), wraplength=560).pack(fill='x', pady=12)
        def accept():
            try: validate_paths(self.input_path.get(), win.vars['output'].get(), self.scope)
            except ValueError as exc: messagebox.showerror(APP_TITLE, str(exc), parent=win); return
            self.output_path.set(os.path.abspath(win.vars['output'].get().strip()))
            win.close()
            if on_done: self.after(10, on_done)
        win.button(label('Cancel', '取消'), win.cancel)
        win.button('Start!', accept)
        return win

    def _capture_config(self):
        return _config_snapshot_payload(
            self.input_path.get(), self.output_path.get(), self.scope,
            self.language, self.volume_level, self.target_mode,
            self.python27_path.get(), self.settings, self.other)

    @staticmethod
    def _merge_loaded_values(target, values):
        """Apply only known setting keys and coerce scalar types."""
        if not isinstance(values, dict):
            return
        for key in list(target):
            if key not in values:
                continue
            value = values[key]
            current = target[key]
            if isinstance(current, bool):
                value = _config_bool(value, current)
            elif isinstance(current, int) and not isinstance(current, bool):
                try:
                    value = int(value)
                except (TypeError, ValueError):
                    continue
            elif isinstance(current, str):
                if isinstance(value, (list, tuple)):
                    value = '; '.join(str(item) for item in value)
                else:
                    value = str(value)
            target[key] = value

    def _apply_config_snapshot(self, data):
        """Load an EasyUI snapshot or a regular CLI YAML configuration."""
        if not isinstance(data, dict):
            raise ValueError('配置文件必须是对象 / Config must be an object')
        state = data if data.get('schema') == CONFIG_SCHEMA else data.get('easyui_state')
        if isinstance(state, dict):
            settings = data.get('settings', data.get('easyui_settings', {}))
            other = data.get('other', data.get('easyui_other', {}))
            self._merge_loaded_values(self.settings, settings)
            self._merge_loaded_values(self.other, other)
            input_path = state.get('input_path', self.input_path.get())
            output_path = state.get('output_path', self.output_path.get())
            scope = state.get('scope', self.scope)
            language = state.get('language', self.language)
            volume = state.get('volume_level', self.volume_level)
            target = state.get('target_mode', self.target_mode)
            python27 = state.get('python27_path', self.python27_path.get())
        else:
            # Accept configs produced by the CLI or older EasyUI versions.
            project = data.get('project', {}) or {}
            basic = data.get('basic', {}) or {}
            source = data.get('source', {}) or {}
            bytecode = data.get('bytecode', {}) or {}
            top = data
            self._merge_loaded_values(self.settings, source)
            self._merge_loaded_values(self.settings, bytecode)
            self._merge_loaded_values(self.other, basic)
            self._merge_loaded_values(self.other, top)
            for key in ('loader_mode', 'loader_dialect', 'loader_vm',
                        'code_tuple_payload', 'code_tuple_field_shuffle',
                        'code_tuple_fragments', 'code_tuple_provider_graph',
                        'code_field_descriptors', 'code_fused_restore',
                        'loader_reference_cleanup', 'code_capsule_proxy',
                        'index_pool_shuffle', 'delayed_const_access'):
                if key in top:
                    if key in self.settings:
                        self.settings[key] = _config_bool(top[key])
                    else:
                        self.other[key] = top[key]
            input_path = project.get('input', top.get('input', self.input_path.get()))
            output_path = project.get('output', top.get('output', self.output_path.get()))
            scope = 'folder' if _config_bool(project.get('folder', top.get('folder', self.scope == 'folder'))) else 'file'
            language = self.language
            volume = top.get('resource_profile', self.volume_level)
            target = 'netease' if str(top.get('opcode_runtime', 'mcs')).lower() == 'mcs' else 'native'
            python27 = top.get('python27', (data.get('runtime', {}) or {}).get('python27', self.python27_path.get()))
        self.input_path.set(str(input_path or ''))
        self.output_path.set(str(output_path or ''))
        self.python27_path.set(str(python27 or ''))
        self.scope = 'file' if scope == 'file' else 'folder'
        if language in ('中文', 'English'):
            self.language = language
        if volume == 'extended':
            volume = 'strong'
        if volume in ('compact', 'balanced', 'strong', 'unlimited'):
            self.volume_level = volume
        if target in ('netease', 'native'):
            self.target_mode = target
        # Use __dict__ here rather than hasattr(): a headless/test instance
        # created before Tk initialization would route hasattr through
        # Tk.Misc.__getattr__ recursively.
        if self.__dict__.get('tree') is not None and self.input_path.get():
            self._refresh_tree(self.input_path.get())
        self._apply_language()

    def save_config(self):
        """Save an exact EasyUI snapshot, optionally as CLI-readable YAML."""
        path = filedialog.asksaveasfilename(
            parent=self, title='保存 MCPArmor 配置 / Save configuration',
            initialdir=STATE_DIR, initialfile='mcparmor_profile.json',
            defaultextension='.json',
            filetypes=[('MCPArmor JSON', '*.json'),
                       ('MCPArmor YAML', '*.yml *.yaml'),
                       ('All files', '*.*')])
        if not path:
            return
        try:
            if not os.path.isdir(os.path.dirname(os.path.abspath(path))):
                os.makedirs(os.path.dirname(os.path.abspath(path)))
            payload = self._capture_config()
            if os.path.splitext(path)[1].lower() in ('.yml', '.yaml'):
                content = self._build_config() + '\n' + _config_yaml_state(payload)
            else:
                payload['cli_config'] = self._build_config()
                content = json.dumps(payload, ensure_ascii=False, indent=2,
                                     sort_keys=True)
            temp = path + '.tmp'
            with open(temp, 'w', encoding='utf-8', newline='') as handle:
                handle.write(content)
            os.replace(temp, path)
            self._set_status(('状态：配置已保存 ' if self.language == '中文' else 'Status: Config saved ') + os.path.basename(path))
        except Exception as exc:
            try:
                if os.path.isfile(path + '.tmp'):
                    os.remove(path + '.tmp')
            except Exception:
                pass
            messagebox.showerror(APP_TITLE, str(exc), parent=self)

    def load_config(self):
        """Load an EasyUI JSON snapshot or any compatible CLI YAML file."""
        path = filedialog.askopenfilename(
            parent=self, title='加载 MCPArmor 配置 / Load configuration',
            initialdir=STATE_DIR,
            filetypes=[('MCPArmor config', '*.json *.yml *.yaml'),
                       ('All files', '*.*')])
        if not path:
            return
        try:
            if os.path.splitext(path)[1].lower() == '.json':
                with open(path, 'r', encoding='utf-8') as handle:
                    data = json.load(handle)
            else:
                data = read_config_file(path)
            self._apply_config_snapshot(data)
            self._set_status(('状态：配置已加载 ' if self.language == '中文' else 'Status: Config loaded ') + os.path.basename(path))
        except Exception as exc:
            messagebox.showerror(APP_TITLE, str(exc), parent=self)

    def open_setting(self, on_done=None, on_cancel=None):
        label = lambda en, cn: cn if self.language == '中文' else en
        win = ScrollDialog(self, label('Obfuscate options', '混淆设置'), on_cancel=on_cancel)
        self._setting_dialog = win
        original = dict(self.settings)
        title = ttk.Frame(win.body); title.pack(fill='x')
        ttk.Label(title, text=label('MCPArmor options', 'MCPArmor 混淆选项'), font=('Segoe UI', 12, 'bold')).pack(side='left')
        ttk.Button(title, text='License...', command=lambda: self.open_license(owner=win)).pack(side='right')
        names = {'off': label('off', '关闭'), 'low': label('low', '低强度'), 'medium': label('medium', '中强度'), 'high': label('high', '高强度')}
        win.field(win.body, 'ast_level', label('AST protection', 'AST 层保护'), names[original['ast_level']], tuple(names.values()))
        win.field(win.body, 'bytecode_level', label('Bytecode protection', '字节码保护'), names[original['bytecode_level']], tuple(names[k] for k in ('low', 'medium', 'high')))
        ttk.Label(win.body, text=label('AST options', 'AST 选项'), font=('Segoe UI', 11, 'bold')).pack(anchor='w', pady=(10, 0))
        win.checks(win.body, AST_CHECKS, original, label)
        strings = ttk.LabelFrame(win.body, text=label('String encryption / splitting', '字符串加密 / 分割'), padding=8); strings.pack(fill='x', pady=8)
        modes = {'random': label('Dynamic XOR', '动态 XOR'), 'text': label('Text key', '文本密钥'), 'number': label('Byte key', '数值密钥'), 'chacha': '_chacha'}
        win.field(strings, 'string_xor_mode', label('Cipher / key mode', '加密 / 密钥模式'), modes[original['string_xor_mode']], tuple(modes.values()))
        win.field(strings, 'string_xor_text', label('Text key', '文本密钥'), original['string_xor_text'])
        for key, en, cn, bounds in (
                ('string_xor_number', 'Byte key', '数值密钥', (0, 255)),
                ('string_xor_min_length', 'Minimum length', '最短加密长度', (0, 100000)),
                ('string_xor_limit', 'Literal limit (0 disables)', '字符串数量上限（0 关闭）', (0, 100000)),
                ('string_xor_variants', 'Decoder variants', '解码器变体', (2, 8)),
                ('string_xor_decoys', 'Decoy variants', '诱饵变体', (0, 8)),
                ('string_split_parts', 'Split parts', '字符串分割份数', (2, 32))):
            win.field(strings, key, label(en, cn), original[key], bounds=bounds)
        win.checks(strings, [('string_xor_debug', 'String debug', '字符串调试')], original, label)
        vm = ttk.LabelFrame(win.body, text=label('VM classes (independent)', 'VM 类（独立选项）'), padding=8); vm.pack(fill='x', pady=8)
        win.checks(vm, VM_CHECKS, original, label)
        ttk.Label(vm, text=label('AST off disables both VM classes. IR applies its full-coverage profile.', 'AST 关闭时两类 VM 均关闭；IR 使用核心的完整覆盖档位。'), wraplength=550).pack(anchor='w')
        for key, en, cn, bounds in (
                ('vm_ratio', 'VM selection %', 'VM 选择比例 %', (0, 100)),
                ('vm_min_ops', 'Minimum operations', '最小操作数', (1, 100000)),
                ('vm_max_ops', 'Maximum operations', '最大操作数', (1, 100000)),
                ('vm_max_functions', 'Function limit (0 unlimited)', '函数上限（0 不限）', (0, 100000)),
                ('vm_dialects', 'VM dialects', 'VM 方言数量', (1, 8)),
                ('vm_exception_trap_ratio', 'Exception trap %', '异常陷阱比例 %', (0, 100))):
            win.field(vm, key, label(en, cn), original[key], bounds=bounds)
        win.field(vm, 'vm_include', label('VM include patterns', 'VM 包含规则'), original['vm_include'])
        win.field(vm, 'vm_exclude', label('VM exclude patterns', 'VM 排除规则'), original['vm_exclude'])
        win.checks(vm, [('vm_allow_loops', 'Allow loops', '允许循环'), ('vm_debug', 'VM debug', 'VM 调试'), ('vm_flow_constants', 'Flow-bound constants', '控制流绑定常量')], original, label)
        byte = ttk.LabelFrame(win.body, text='ByteCode_Flow', padding=8); byte.pack(fill='x', pady=8)
        win.field(byte, 'flow_ratio', label('Flow density %', '控制流密度 %'), original['flow_ratio'], bounds=(0, 100))
        win.field(byte, 'flow_max_edges', label('Maximum edges', '最大边数'), original['flow_max_edges'], bounds=(1, 12))
        win.checks(byte, BYTE_CHECKS, original, label)
        advanced_open = tk.BooleanVar(win, value=False)
        advanced_toggle = ttk.Checkbutton(win.body, text=label('Show advanced bytecode options', '显示高级字节码选项'), variable=advanced_open)
        advanced_toggle.pack(anchor='w', pady=6)
        advanced = ttk.LabelFrame(win.body, text=label('Advanced bytecode options', '高级字节码选项'), padding=8)
        win.checks(advanced, ADVANCED_BYTE_CHECKS, original, label)
        def toggle_advanced():
            if advanced_open.get(): advanced.pack(fill='x', pady=6)
            else: advanced.pack_forget()
        advanced_toggle.configure(command=toggle_advanced)
        win.controls['advanced_toggle'] = advanced_toggle
        win.controls['advanced_frame'] = advanced
        def set_level(which):
            key = next(k for k, v in names.items() if v == win.vars[which].get())
            fields = AST_CHECKS if which == 'ast_level' else BYTE_CHECKS + ADVANCED_BYTE_CHECKS
            defaults = AST_DEFAULTS[key] if which == 'ast_level' else BYTE_DEFAULTS[key]
            for name, _, _ in fields: win.vars[name].set(bool(defaults.get(name, False)))
            if which == 'bytecode_level':
                for name in ('flow_ratio', 'flow_max_edges'): win.vars[name].set(str(defaults[name]))
        for which in ('ast_level', 'bytecode_level'):
            win.controls[which].bind('<<ComboboxSelected>>', lambda e, key=which: set_level(key))
        def apply_values():
            try:
                updated = dict(original)
                for key, var in win.vars.items():
                    value = var.get()
                    if key in ('ast_level', 'bytecode_level'): value = next(k for k, v in names.items() if v == value)
                    elif key == 'string_xor_mode': value = next(k for k, v in modes.items() if v == value)
                    elif isinstance(original.get(key), int) and not isinstance(original[key], bool):
                        value = int(value)
                        control = win.controls[key]
                        if not int(float(control.cget('from'))) <= value <= int(float(control.cget('to'))): raise ValueError(key)
                    updated[key] = value
                if updated['vm_min_ops'] > updated['vm_max_ops']: raise ValueError('VM min > max')
                self.settings = updated
                self._set_status(label('Status: Settings applied', '状态：设置已应用'))
                return True
            except (ValueError, tk.TclError) as exc:
                messagebox.showerror(APP_TITLE, label('Invalid setting: ', '设置值无效：') + str(exc), parent=win)
                return False
        def previous():
            for key, var in win.vars.items():
                value = original[key]
                if key in ('ast_level', 'bytecode_level'): value = names[value]
                elif key == 'string_xor_mode': value = modes[value]
                var.set(value)
        def ok():
            if apply_values():
                win.close()
                if on_done: self.after(10, on_done)
        win.button(label('Cancel', '取消'), win.cancel)
        win.button(label('Apply', '应用'), apply_values)
        win.button(label('OK', '确定'), ok)
        win.button(label('Previous', '上一步'), previous, side='left')
        return win

    def open_license(self, owner=None):
        win = ScrollDialog(owner or self, 'License', 660, 330)
        logo = _logo_image(5)
        if logo:
            win.logo = logo
            ttk.Label(win.body, image=logo).pack(anchor='w')
        else: ttk.Label(win.body, text=APP_TITLE, font=('Segoe UI', 18, 'bold')).pack(anchor='w')
        ttk.Label(win.body, text='version %s\n%s\n%s' % (APP_VERSION, COPYRIGHT, SITE)).pack(anchor='w', pady=8)
        for key, value in [('HWID', self.hwid), ('Time', self.expiry)]:
            win.field(win.body, key, key, value).configure(state='readonly')
        win.button('OK', win.close)
        return win

    def open_lang(self):
        win = ScrollDialog(self, 'Language / 语言', 410, 240)
        win.field(win.body, 'language', 'Language / 语言', self.language, ('English', '中文'))
        def ok():
            self.language = win.vars['language'].get(); self._apply_language(); win.close()
        win.button('Cancel / 取消', win.cancel)
        win.button('OK / 确定', ok)
        return win

    def open_loader(self, on_done=None, on_cancel=None):
        """Configure the payload loader independently from AST/bytecode."""
        label = lambda en, cn: cn if self.language == '中文' else en
        win = ScrollDialog(self, label('Loader settings', '加载器设置'), 680, 540, on_cancel)
        self._loader_dialog = win
        mode = self.other.get('loader_mode', 'cpickle')
        win.field(win.body, 'loader_mode', label('Loader mode', '加载器模式'), mode,
                  ('cpickle', 'netease-func', 'function', 'marshal', 'source'))
        win.field(win.body, 'loader_dialect', label('Loader dialect', '加载器方言'), self.other.get('loader_dialect', 'auto'), ('auto', '0', '1', '2'))
        win.checks(win.body, [
            ('loader_vm', 'Loader crypto VM', '加载器 VM（加密运行时）'),
            ('code_tuple_payload', 'CodeTuple payload', 'CodeTuple 载荷'),
            ('code_tuple_field_shuffle', 'Shuffle CodeTuple fields', 'CodeTuple 字段乱序'),
            ('code_tuple_fragments', 'Fragment CodeTuple fields', 'CodeTuple 字段碎片化'),
            ('code_tuple_provider_graph', 'Provider graph', 'Provider 图'),
            ('code_field_descriptors', 'Field descriptors', '字段描述符'),
            ('code_fused_restore', 'Fused restore', '融合恢复'),
            ('loader_reference_cleanup', 'Reference cleanup', '引用清理'),
            ('code_capsule_proxy', 'Capsule proxy', '代码胶囊代理'),
            ('index_pool_shuffle', 'Index pool shuffle', '索引池乱序'),
            ('delayed_const_access', 'Delayed constants', '延迟常量访问'),
        ], dict(self.other, **self.settings), label)
        ttk.Label(win.body, text=label(
            'cpickle uses recursive CodeTuple payloads. Disable CodeTuple to compare direct loader behavior; Loader VM is independent.',
            'cpickle 使用递归 CodeTuple 载荷。关闭 CodeTuple 可对比直接加载器行为；加载器 VM 与载荷格式独立。'),
                  wraplength=570).pack(anchor='w', pady=10)
        def ok():
            selected = win.vars['loader_mode'].get()
            self.other['loader_mode'] = selected
            self.other['loader_dialect'] = win.vars['loader_dialect'].get()
            self.other['loader_vm'] = bool(win.vars['loader_vm'].get())
            for key in ('code_tuple_payload', 'code_tuple_field_shuffle',
                        'code_tuple_fragments', 'code_tuple_provider_graph',
                        'code_field_descriptors', 'code_fused_restore',
                        'loader_reference_cleanup', 'code_capsule_proxy',
                        'index_pool_shuffle', 'delayed_const_access'):
                if key in win.vars:
                    if key in self.settings:
                        self.settings[key] = bool(win.vars[key].get())
                    else:
                        self.other[key] = bool(win.vars[key].get())
            win.close()
            self._set_status(label('Status: Loader settings updated', '状态：加载器设置已更新'))
            if on_done: self.after(10, on_done)
        win.button(label('Cancel', '取消'), win.cancel)
        win.button(label('OK', '确定'), ok)
        return win

    def open_other(self, on_done=None, on_cancel=None):
        label = lambda en, cn: cn if self.language == '中文' else en
        win = ScrollDialog(self, label('Other settings', '其他设置'), 660, 560, on_cancel)
        self._other_dialog = win
        target_names = {'netease': label('NetEase (MCS)', '网易（MCS）'), 'native': label('Native (STD)', '原生（STD）')}
        volume_names = {'compact': label('Compact', '紧凑'), 'balanced': label('Balanced', '平衡'), 'strong': label('Extended', '扩展'), 'unlimited': label('Unlimited', '不限')}
        win.field(win.body, 'target_mode', label('Runtime', '运行模式'), target_names[self.target_mode], tuple(target_names.values()))
        volume = 'strong' if self.volume_level == 'extended' else self.volume_level
        win.field(win.body, 'volume_level', label('Volume profile', '体积档位'), volume_names[volume], tuple(volume_names.values()))
        win.field(win.body, 'mcs_opmap_version', label('MCS opcode map', 'MCS opcode 映射'), self.other['mcs_opmap_version'], (0, 1))
        win.field(win.body, 'output_date', label('Output date', '输出日期'), self.other['output_date'])
        win.field(win.body, 'python27', 'Python 2.7', self.python27_path.get())
        ttk.Button(win.body, text=label('Browse Python 2.7', '浏览 Python 2.7'), command=lambda: win.vars['python27'].set(filedialog.askopenfilename(parent=win, filetypes=[('Python', '*.exe')]) or win.vars['python27'].get())).pack(anchor='e')
        ttk.Label(win.body, text=label('Used by the Python 2.7 target worker, not by the UI itself.', '供 Python 2.7 目标 worker 使用，不是 UI 自身的解释器。'), wraplength=540).pack(anchor='w', pady=6)
        win.checks(win.body, [
            ('no_bytecode_obf', 'Disable bytecode obfuscation', '关闭字节码混淆'),
            ('opcode_replacement', 'Enable opcode replacement', '启用 opcode 替换（STD / MCS）'),
            ('debug', 'Debug mode', '调试模式'), ('log_enabled', 'Write diagnostic log', '写入诊断日志'),
            ('write_rename_mapping', 'Export ProGuard-style mapping', '输出类名 / 文件名映射（ProGuard 格式）'),
            ('clean_output', 'Clean output directory', '清理输出目录'),
            ('anti_debug', 'AntiDebug (_chacha + UUID)', 'AntiDebug（_chacha + UUID）')], self.other, label)
        for key, en, cn in (
            ('exclude', 'Exclude obfuscation', '排除文件混淆'),
            ('ast_exclude', 'Exclude AST only', '仅排除 AST 混淆'),
            ('source_only', 'Exclude bytecode only', '仅排除字节码混淆'),
            ('module_rename_exclude', 'Keep file / folder names', '保留文件 / 文件夹名称')):
            win.field(win.body, key, label(en, cn), self.other[key])
        ttk.Label(win.body, text=label('Separate patterns with ; or , (e.g. modMain.py; ui/*.py). Static checking stays enabled.', '使用分号或逗号分隔规则，如 modMain.py; ui/*.py。静态检查始终开启。'), wraplength=540).pack(anchor='w', pady=8)
        def ok():
            try:
                values = {key: var.get() for key, var in win.vars.items()}
                date = values['output_date'].strip() or '2012-03-15'
                datetime.datetime.strptime(date, '%Y-%m-%d')
                # Read display values once before mapping them. Calling pop()
                # from a generator removes the key on the first comparison;
                # subsequent comparisons then raise KeyError.
                target_display = values.pop('target_mode')
                volume_display = values.pop('volume_level')
                mode = next(k for k, v in target_names.items() if v == target_display)
                volume = next(k for k, v in volume_names.items() if v == volume_display)
                py27 = values.pop('python27').strip()
                values['mcs_opmap_version'] = int(values['mcs_opmap_version'])
                values['output_date'] = date
            except (ValueError, tk.TclError) as exc:
                messagebox.showerror(APP_TITLE, label('Invalid setting: ', '设置值无效：') + str(exc), parent=win); return
            self.other.update(values)
            self.target_mode, self.volume_level = mode, volume
            self.python27_path.set(py27)
            win.close()
            if on_done: self.after(10, on_done)
        win.button(label('Cancel', '取消'), win.cancel)
        win.button(label('OK', '确定'), ok)
        return win

    def _prompt_qlearn(self):
        text = ('需要 QLearn 快速引导吗？\n输入 → 混淆设置 → 加载器 → 其他设置 → 输出 / 混淆 → 完成' if self.language == '中文' else
                'Start QLearn quick guide?\nInput → Setting → Loader → Other → Output / Obf → Finish')
        if messagebox.askyesno('QLearn', text, parent=self): self.open_qlearn()

    def open_qlearn(self):
        if self.running or self._qlearn_active: return
        self._qlearn_active = True
        self._qlearn_advance('input')

    def _qlearn_cancel(self):
        self._qlearn_active = False
        self._qlearn_step = None
        self._obf_done_callback = None
        self._set_status('状态：QLearn 已取消' if self.language == '中文' else 'Status: QLearn cancelled')

    def _qlearn_advance(self, step):
        if not self._qlearn_active: return
        self._qlearn_step = step
        self._set_status('Status: QLearn - ' + step)
        if step == 'input': self.open_input(lambda: self._qlearn_advance('setting'), self._qlearn_cancel)
        elif step == 'setting': self.open_setting(lambda: self._qlearn_advance('loader'), self._qlearn_cancel)
        elif step == 'loader': self.open_loader(lambda: self._qlearn_advance('other'), self._qlearn_cancel)
        elif step == 'other': self.open_other(lambda: self._qlearn_advance('obf'), self._qlearn_cancel)
        elif step == 'obf': self.open_obf(on_done=self._qlearn_finish, on_cancel=self._qlearn_cancel)

    def _qlearn_finish(self, code):
        self._qlearn_active = False
        self._qlearn_step = 'finish'
        if code == 0:
            self._set_status('状态：QLearn 完成' if self.language == '中文' else 'Status: QLearn finished')
            messagebox.showinfo('QLearn', '混淆完成，左侧显示产物。' if self.language == '中文' else 'Finished. The tree now shows the output.', parent=self)
        else:
            self._set_status('Status: QLearn - Failed (%s) - Log' % code)
            messagebox.showerror('QLearn', ('混淆失败，退出码 %s。请打开 Log 查看完整错误。' if self.language == '中文' else 'Failed with exit code %s. Open Log for details.') % code, parent=self)

    def open_about(self):
        messagebox.showinfo(APP_TITLE, '%s %s\n%s\n%s' % (APP_TITLE, APP_VERSION, COPYRIGHT, SITE), parent=self)

    def open_update_log(self):
        """Show version notes in a separate scrollable window."""
        zh = self.language == '中文'
        win = ScrollDialog(self, '更新日志' if zh else 'Update log', 720, 500)
        if zh:
            notes = ('MCPArmor 3.6 更新内容\n\n'
                     '• 新增 ZKM 风格主界面与许可证窗口\n'
                     '• 新增 QLearn 快速引导流程\n'
                     '• 新增独立 Loader 设置：cPickle、Loader VM、CodeTuple\n'
                     '• 新增 AST / ByteCode_Flow 分级设置\n'
                     '• 新增输入输出路径校验与文件夹拖入\n'
                     '• 新增类 / 函数树、产物树和逐文件进度显示\n'
                     '• 新增失败文件与日志定位\n'
                     '• 修复 Python 2.7 / 3.13 配置同步\n'
                     '• 修复 Loader VM 被强制开启、ChaCha 密钥长度和 AST 兼容问题\n\n'
                     '• 新增配置保存 / 加载：JSON 精确快照与 CLI YAML 兼容导入\n'
                     '• 配置功能使用独立“配置”菜单，包含保存配置与加载配置\n'
                     '• 新增配置版本校验、原子写入与重启后状态恢复\n'
                     '• 新增 ZKM 风格 Region Router、边级路径状态和局部槽位置换\n'
                     '• 新增每函数状态代数多态与条件跳转极性变换\n'
                     '• 新增变换后 Frame proof 与组合回滚\n\n'
                     '• 3.4：Region Router 与边级路径状态\n'
                     '• 3.5：每函数状态代数与真实局部槽位置换\n'
                     '• 3.6：调用级 nonce、语义指令模板和流结构审计\n\n'
                     '• 修复不限模式小文件强度过低，并修复函数分割后的 RegisterUI 链接审计\n\n'
                     '当前版本：3.6')
        else:
            notes = ('MCPArmor 3.6 Update log\n\n'
                     '• Added compact ZKM-style workspace and license dialog\n'
                     '• Added QLearn guided workflow\n'
                     '• Added independent Loader settings: cPickle, Loader VM and CodeTuple\n'
                     '• Added AST / ByteCode_Flow strength profiles\n'
                     '• Added path validation and Explorer folder drop\n'
                     '• Added classes/functions, artifact tree and per-file progress\n'
                     '• Added failed-file and log reporting\n'
                     '• Fixed Python 2.7 / 3.13 configuration synchronization\n'
                     '• Fixed Loader VM, ChaCha key-size and AST compatibility issues\n\n'
                     '• Added JSON snapshot save/load and CLI YAML import compatibility\n'
                     '• Added a separate Configuration menu for Save and Load\n'
                     '• Added versioned config validation, atomic writes and state restore\n'
                     '• Added ZKM-style Region Router, edge path state and local-slot permutation\n'
                     '• Added per-function state algebra and conditional polarity variation\n'
                     '• Added post-transform Frame proof and transactional composition rollback\n\n'
                     '• 3.4: Region Router and edge path state\n'
                     '• 3.5: Per-function state algebra and real local-slot permutation\n'
                     '• 3.6: Call-level nonce, semantic templates and flow audit metrics\n\n'
                     '• Fixed weak unlimited-mode small files and RegisterUI link audits after function splitting\n\n'
                     'Current version: 3.6')
        text = tk.Text(win.body, wrap='word', height=22, font=('Segoe UI', 10), relief='flat')
        text.pack(fill='both', expand=True)
        text.insert('1.0', notes)
        text.configure(state='disabled')
        win.button('关闭' if zh else 'Close', win.close)
        return win

    def open_log(self):
        label = lambda en, cn: cn if self.language == '中文' else en
        win = ScrollDialog(self, label('Log', '日志'), 820, 540)
        frame = ttk.Frame(win.body); frame.pack(fill='both', expand=True)
        frame.columnconfigure(0, weight=1); frame.rowconfigure(0, weight=1)
        text = tk.Text(frame, height=22, wrap='none', font=('Consolas', 9))
        text.grid(row=0, column=0, sticky='nsew')
        sy = ttk.Scrollbar(frame, command=text.yview); sy.grid(row=0, column=1, sticky='ns')
        sx = ttk.Scrollbar(frame, orient='horizontal', command=text.xview); sx.grid(row=1, column=0, sticky='ew')
        text.configure(yscrollcommand=sy.set, xscrollcommand=sx.set)
        def refresh():
            if not win.winfo_exists(): return
            content = self.last_run_output
            if not content and os.path.isfile(RUN_LOG):
                with open(RUN_LOG, encoding='utf-8', errors='replace') as f: content = f.read()
            if content != getattr(win, '_last_content', None):
                win._last_content = content
                text.configure(state='normal'); text.delete('1.0', 'end'); text.insert('1.0', content or '(empty)'); text.configure(state='disabled'); text.see('end')
        def poll():
            if win.winfo_exists():
                refresh(); win.after(300, poll)
        poll()
        win.button(label('Close', '关闭'), win.close)
        win.button(label('Refresh', '刷新'), refresh, side='left')
        return win

    def _build_config(self):
        s, other = self.settings, self.other
        ast_on = s['ast_level'] != 'off'
        byte_on = not other['no_bytecode_obf']
        mapped = byte_on and bool(other['opcode_replacement'])
        mcs = self.target_mode == 'netease'
        source = {key: ast_on and bool(s[key]) for key, _, _ in AST_CHECKS}
        source['module_rename'] = source['module_rename'] and self.scope == 'folder'
        source['function_split'] = source['function_split'] and self.scope == 'folder'
        source.update(project_analysis=ast_on, vm=False,
                      vm_ir=ast_on and bool(s['vm_ir']), vm_extension=ast_on and bool(s['vm_extension']))
        for key in s:
            if key.startswith('vm_') and key not in ('vm_ir', 'vm_extension'):
                source[key] = split_patterns(s[key]) if key in ('vm_include', 'vm_exclude') else s[key]
            if key.startswith('string_xor_') or key == 'string_split_parts': source[key] = s[key]
        if not ast_on or not (s['vm_ir'] or s['vm_extension']): source['vm_ratio'] = 0
        source['module_rename_exclude'] = split_patterns(other['module_rename_exclude'])
        source['ast_exclude'] = split_patterns(other['ast_exclude'])
        bytecode = {key: byte_on and bool(s[key]) for key, _, _ in BYTE_CHECKS + ADVANCED_BYTE_CHECKS}
        bytecode.update(enabled=byte_on, flow=byte_on, flow_ratio=s['flow_ratio'], flow_max_edges=s['flow_max_edges'],
                        opcode_replacement=mapped, opcode_runtime='mcs' if mcs else 'std',
                        mcs_opmap_version=other['mcs_opmap_version'] if mcs else 0,
                        code_tuple_payload=bool(s.get('code_tuple_payload', other.get('code_tuple_payload', True))), source_only=split_patterns(other['source_only']))
        # The compact cpickle preset forces MCS mapping in the existing core.
        # Use the CodeTuple/cPickle function loader when mapping is disabled or STD is selected.
        loader = other.get('loader_mode', 'cpickle')
        payload = bool(s.get('code_tuple_payload', other.get('code_tuple_payload', True)))
        sections = [('project', [('input', self.input_path.get()), ('output', self.output_path.get()),
                    ('folder', self.scope == 'folder'), ('include', ['*.py']), ('exclude', split_patterns(other['exclude'])),
                    ('clean_output', other['clean_output'])]),
                    ('source', list(source.items())), ('bytecode', list(bytecode.items()))]
        # Top-level keys match the CLI aliases exactly; unknown nested aliases used to disappear silently.
        top = dict(preset='none', resource_profile={'extended': 'strong'}.get(self.volume_level, self.volume_level),
                   loader_mode=loader, loader_dialect=other.get('loader_dialect', 'auto'),
                   loader_vm=other.get('loader_vm', False), code_tuple_payload=payload,
                   output_date=other['output_date'], debug=other['debug'],
                   static_check=True, python27=self.python27_path.get().strip() or None,
                   anti_debug=other.get('anti_debug', False), key_len=16,
                   write_rename_mapping=other['write_rename_mapping'],
                   netease_profile='none', fix_netease_register=mcs)
        return _yaml(sections) + ''.join('%s: %s\n' % (key, 'null' if value is None else _scalar(value)) for key, value in top.items())

    def open_obf(self, on_done=None, on_cancel=None):
        if self.running: return
        self._obf_done_callback = on_done
        self._obf_cancel_callback = on_cancel
        self.open_output(self._show_obf_confirm, self._cancel_obf)

    def _cancel_obf(self):
        callback = getattr(self, '_obf_cancel_callback', None)
        self._obf_done_callback = None
        self._obf_cancel_callback = None
        if callback: callback()

    def _show_obf_confirm(self):
        label = lambda en, cn: cn if self.language == '中文' else en
        win = ScrollDialog(self, label('Confirm obfuscation', '确认混淆'), 690, 520, self._cancel_obf)
        ttk.Label(win.body, text=label('Confirm your output, backup and config before starting.', '启动前请确认输出位置、备份和配置。'), wraplength=560).pack(anchor='w')
        text = tk.Text(win.body, height=14, wrap='word', font=('Consolas', 9))
        text.pack(fill='both', expand=True, pady=8)
        text.insert('1.0', self._build_config()); text.configure(state='disabled')
        backup, reviewed = tk.BooleanVar(win), tk.BooleanVar(win)
        def gate(): start.configure(state='normal' if backup.get() and reviewed.get() else 'disabled')
        ttk.Checkbutton(win.body, text=label('I have backed up the source', '已备份源文件'), variable=backup, command=gate).pack(anchor='w')
        ttk.Checkbutton(win.body, text=label('I reviewed the config', '已检查配置'), variable=reviewed, command=gate).pack(anchor='w')
        def launch():
            if self._launch_obf(): win.close()
        win.button(label('Cancel', '取消'), win.cancel)
        start = win.button('Start!', launch); start.configure(state='disabled')
        return win

    def _launch_obf(self):
        if self.running: return False
        try:
            validate_paths(self.input_path.get(), self.output_path.get(), self.scope)
            os.makedirs(STATE_DIR, exist_ok=True)
            with open(RUN_CONFIG, 'w', encoding='utf-8') as handle: handle.write(self._build_config())
            # Source mode must not accidentally run an older packaged CLI.
            packaged = bool(getattr(sys, 'frozen', False) or '__compiled__' in globals())
            cli = _find_cli() if packaged else None
            if packaged and not cli: raise FileNotFoundError('CLI executable missing next to the UI')
            cwd = os.path.dirname(cli) if cli else ROOT_DIR
            argv = [cli, '--config', RUN_CONFIG] if cli else [sys.executable, '-m', 'MCP_Armor_Src', '--config', RUN_CONFIG]
            context = dict(output=self.output_path.get().strip(), log=bool(self.other['log_enabled']), env=os.environ.copy())
            if self.python27_path.get().strip(): context['env']['MCPARMOR_PY27'] = self.python27_path.get().strip()
            self.last_run_output = '$ ' + subprocess.list2cmdline(argv) + '\n'
            self._file_progress = None
            self.running = True
            self._set_status('状态：运行中' if self.language == '中文' else 'Status: Running')
            threading.Thread(target=self._worker, args=(argv, cwd, context), daemon=True).start()
            return True
        except Exception:
            self.running = False
            self.last_run_output = traceback.format_exc()
            messagebox.showerror(APP_TITLE, self.last_run_output, parent=self)
            return False

    def _worker(self, argv, cwd, context):
        # Only plain data crosses the thread boundary; no Tk variables or dialogs.
        chunks = ['$ ' + subprocess.list2cmdline(argv) + '\n']
        try:
            kwargs = dict(cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                          env=context['env'], text=True, encoding='utf-8', errors='replace')
            if os.name == 'nt': kwargs['creationflags'] = subprocess.CREATE_NO_WINDOW
            with subprocess.Popen(argv, **kwargs) as proc:
                for line in proc.stdout:
                    chunks.append(line)
                    self.events.put(('log', line))
                    progress = parse_progress(line)
                    if progress is not None:
                        self.events.put(('progress', progress))
                code = proc.wait()
        except Exception:
            chunks.append(traceback.format_exc()); code = 1
        chunks.append('\nExit code: %s\n' % code)
        data = ''.join(chunks)
        if context['log']:
            try:
                os.makedirs(STATE_DIR, exist_ok=True)
                with open(RUN_LOG, 'w', encoding='utf-8') as handle: handle.write(data)
            except OSError as exc: data += '\nLog write error: %s' % exc
        self.events.put(('run', code, data, context['output']))

    def _poll_events(self):
        try:
            while True:
                self._accept_drop(self._drop_queue.get_nowait())
        except queue.Empty:
            pass
        try:
            while True:
                event = self.events.get_nowait()
                if event[0] == 'license':
                    _kind, self.hwid, self.expiry = event
                    splash = getattr(self, '_license_splash', None)
                    if splash is not None and splash.winfo_exists(): splash.set_expiry(self.expiry)
                elif event[0] == 'log':
                    self.last_run_output += event[1]
                elif event[0] == 'progress':
                    self._update_file_progress(event[1])
                elif event[0] == 'run':
                    _kind, code, data, artifact_root = event
                    self.running = False
                    self.last_run_output = data
                    if code == 0:
                        # The left pane is an artifact browser: once output is
                        # produced, show its renamed files/classes/functions.
                        if artifact_root and os.path.exists(artifact_root):
                            self._refresh_tree(artifact_root)
                        self._set_status('Status: Finished - showing output symbols')
                    else:
                        self._set_status('Status: Failed (%s) - Log' % code)
                        self.open_log()
                    callback = self._obf_done_callback
                    self._obf_done_callback = None
                    self._obf_cancel_callback = None
                    if callback: callback(code)
        except queue.Empty:
            pass
        self.after(100, self._poll_events)


def main():
    EasyApp().mainloop()


if __name__ == '__main__':
    main()\n