# -*- coding: utf-8 -*-
"""Remote encrypted-HWID license table and expiration validation."""


import calendar
import datetime
import io
import json
import os
import sys
from MCP_Armor_Src.hwid.machine import encrypted_hwid
from MCP_Armor_Src.hwid.network import fetch_json
from MCP_Armor_Src.hwid.time_source import taobao_timestamp


LICENSE_URL = (
    'https://gitee.com/online-ah/mini-world_-obf/raw/master/hwid.json')
LOCAL_LICENSE_NAMES = ('i.txt', 'hwid.json')
FREE_MODE_REASON = 'free_mode'
CHINA_UTC_OFFSET_SECONDS = 8 * 60 * 60

try:
    _STRING_TYPES = (basestring,)
except NameError:
    _STRING_TYPES = (str,)


class LicenseStatus(object):
    def __init__(self, valid, code, reason, expires=None, source=None):
        self.valid = bool(valid)
        self.code = code
        self.reason = reason
        self.expires = expires
        self.source = source


def get_license_url():
    return LICENSE_URL


def _unique_paths(paths):
    """Return existing candidate paths once, preserving priority order."""
    result = []
    seen = set()
    for path in paths:
        if not path:
            continue
        path = os.path.abspath(os.path.expanduser(path))
        marker = os.path.normcase(path)
        if marker in seen:
            continue
        seen.add(marker)
        result.append(path)
    return result


def get_local_license_path():
    """Locate an optional local ``i.txt``/``hwid.json`` license payload.

    ``MCPARMOR_HWID_FILE`` has highest priority so packaged applications can
    select a deployment-specific policy.  Next we inspect the executable
    directory, current working directory, and source/package roots.  A local
    file is deliberately optional; the remote URL remains the final fallback.
    """
    override = os.environ.get('MCPARMOR_HWID_FILE')
    candidates = []
    if override:
        candidates.append(override)

    executable = ''
    try:
        executable = os.path.abspath(sys.argv[0]) if sys.argv else ''
    except Exception:
        executable = ''
    executable_dir = os.path.dirname(executable) if executable else ''
    source_root = os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    bases = (executable_dir, os.getcwd(), source_root,
             os.path.dirname(os.path.abspath(__file__)))
    for base in bases:
        for name in LOCAL_LICENSE_NAMES:
            candidates.append(os.path.join(base, name))
    for path in _unique_paths(candidates):
        if os.path.isfile(path):
            return path
    return None


def _load_local_payload(path):
    # ``io.open`` keeps this path compatible with Python 2 workers and UTF-8
    # files containing a BOM generated by desktop editors.
    with io.open(path, 'r', encoding='utf-8-sig') as stream:
        return json.load(stream)


def _is_free_mode(payload):
    """Return True only when the JSON policy explicitly enables isFree."""
    if not isinstance(payload, dict):
        return False
    value = payload.get('isFree', False)
    if isinstance(value, bool):
        return value
    if isinstance(value, _STRING_TYPES):
        return value.strip().lower() in ('true', '1', 'yes', 'on')
    return bool(value)


def _load_payload(source):
    if source and os.path.isfile(source):
        return _load_local_payload(source)
    return fetch_json(source, timeout=8, no_cache=True)


def is_free_mode():
    """Inspect the local policy without collecting a machine fingerprint."""
    path = get_local_license_path()
    if not path:
        return False
    try:
        return _is_free_mode(_load_local_payload(path))
    except Exception:
        return False


def _normalize_code(value):
    return ''.join(str(value or '').replace('-', '').split()).upper()


def _parse_expiration(value):
    if isinstance(value, (int, float)):
        stamp = float(value)
        return (stamp / 1000.0 if stamp > 100000000000.0 else stamp), str(value)
    text = str(value or '').strip()
    if text.isdigit():
        stamp = float(text)
        return (stamp / 1000.0 if stamp > 100000000000.0 else stamp), text
    formats = (
        ('%Y-%m-%d %H:%M:%S', False),
        ('%Y-%m-%dT%H:%M:%S', False),
        ('%Y-%m-%dT%H:%M:%SZ', True),
        ('%Y-%m-%d', False),
    )
    for pattern, utc in formats:
        try:
            parsed = datetime.datetime.strptime(text, pattern)
        except ValueError:
            continue
        if pattern == '%Y-%m-%d':
            parsed = parsed.replace(hour=23, minute=59, second=59)
        stamp = calendar.timegm(parsed.timetuple())
        if not utc:
            stamp -= CHINA_UTC_OFFSET_SECONDS
        return float(stamp), text
    raise ValueError('invalid expiration time: %s' % text)


def _normalize_table(payload):
    table = payload.get('hwid') if isinstance(payload, dict) else None
    if not isinstance(table, dict):
        raise ValueError('license JSON must contain an hwid object')
    return dict((_normalize_code(key), expiration)
                for key, expiration in list(table.items()))


def validate_license(license_url=None, now=None, code=None, table=None):
    # An explicit table is used by deterministic callers/tests and must not be
    # replaced by a local deployment policy.  Normal runs prefer the local
    # policy file, then fall back to the existing remote endpoint.
    source = license_url
    if table is None:
        source = source or get_local_license_path() or get_license_url()
        try:
            table = _load_payload(source)
        except Exception as exc:
            reason = ('license_data_invalid:%s' % exc
                      if os.path.isfile(source)
                      else 'license_server_unavailable:%s' % exc)
            return LicenseStatus(False, _normalize_code(code), reason,
                                 source=source)
    elif source is None:
        source = '<inline>'

    # isFree is a policy switch, not a HWID entry.  Resolve it before calling
    # encrypted_hwid so free mode genuinely bypasses machine fingerprinting,
    # network time, and all authorization-table checks (including the CLI).
    if _is_free_mode(table):
        return LicenseStatus(True, _normalize_code(code), FREE_MODE_REASON,
                             source=source)

    code = _normalize_code(code or encrypted_hwid())
    try:
        table = _normalize_table(table)
    except (TypeError, ValueError) as exc:
        return LicenseStatus(False, code, 'license_data_invalid:%s' % exc,
                             source=source)
    if code not in table:
        return LicenseStatus(False, code, 'hwid_not_authorized', source=source)
    try:
        expires_at, expires_text = _parse_expiration(table[code])
    except (TypeError, ValueError) as exc:
        return LicenseStatus(False, code, 'expiration_invalid:%s' % exc,
                             source=source)
    if now is None:
        try:
            now = taobao_timestamp()
        except Exception as exc:
            return LicenseStatus(False, code, 'time_server_unavailable:%s' % exc,
                                 expires_text, source)
    if float(now) > expires_at:
        return LicenseStatus(False, code, 'license_expired', expires_text,
                             source)
    return LicenseStatus(True, code, 'ok', expires_text, source)


def format_cli_failure(status):
    if status.reason == 'license_expired':
        title = 'HWID license expired; please renew your license.'
    elif status.reason == 'hwid_not_authorized':
        title = 'HWID is not authorized; please request or renew a license.'
    elif status.reason.startswith('license_server_unavailable:'):
        title = 'HWID license server is unavailable.'
    elif status.reason.startswith('time_server_unavailable:'):
        title = 'Taobao time API is unavailable; license cannot be verified.'
    else:
        title = 'HWID license validation failed: %s' % status.reason
    rows = [title, 'HWID: %s' % status.code]
    if status.expires:
        rows.append('EXPIRES: %s' % status.expires)
    if status.source:
        rows.append('LICENSE_SERVER: %s' % status.source)
    return '\n'.join(rows)\n